### PR TITLE
Initial create-react-app setup

### LINKED ISSUE #2168: V.2: Planned roadway for version 2
**For the development of V.2, TDD(Test Driven Development) approach should opt**

- [ ] Implement **Django Server with API-Blueprint using Swagger or Apiary.**
- [ ] Implement **ReactJS FrontEnd**, Framework can be decided later on.
- [ ] Implement CD and other Cloud Functions

### PR DESCRIPTION
**Pull request by godcrampy**
Fixes #2168 

#### Short description of what this resolves:
Basic setup of ReactJs for front-end.

#### Changes proposed in this pull request:

- Created initial front-end setup for V2 using ```create-react-app```
- Updated ```package.json``` to match the master branch

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes  
- [x] I have added tests that prove my fix is effective or that my feature works (Not Applicable)
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by kushthedude** [comment]
Not requires currently.

**Comment by kushthedude** [comment]
Please follow the Gitter chat. Thanks

**Comment by godcrampy** [comment]
I am not exactly clear why this PR was closed. I am following the glitter chat. It was mentioned there for react and django setup. Is someone else working on this issue? Please clarify my confusion.

**Comment by kushthedude** [comment]
> I am not exactly clear why this PR was closed. I am following the glitter chat. It was mentioned there for react and django setup. Is someone else working on this issue? Please clarify my confusion.

Server will be implemented before the FE

**Pull request closed without merging**
