### PR TITLE
Fixes #77 to make the page responsive

### LINKED ISSUE #77: Page not responsive
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/badgeyay

**Current behavior:**
The page is not responsive, gets distorted for smaller screen sizes.

**Expected behavior:**
The page should be responsive.

**Steps to reproduce:**
screen shot 2017-09-17 at 11 40 37 am

### PR DESCRIPTION
**Pull request by sounak98**
Fixes #77 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

- [x] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:
This makes the page responsive.

#### Changes proposed in this pull request:

- Makes the page responsive

### CODE REVIEW

**Comment by sounak98** [comment]
The test is failing because `selenium` isn't getting installed as a pre-requisite for Travis CI.

**Comment by sounak98** [comment]
## Screenshots for review
### On smaller screens
screen shot 2017-09-17 at 10 10 03 pm
### On larger screens
screen shot 2017-09-17 at 10 09 46 pm

**Comment by gabru-md** [comment]
This looks very good.
Great work!

**Comment by gabru-md** [comment]
If you could please squash your commits into one then it would be great! 
:+1:

**Comment by niccokunzmann** [comment]
@sounak98 Thanks for your pull-request! @gabru-md You can merge, when you think it is fine, you can even merge if you do not know if it is fine. If in doubt, trust :)

**Pull request merged**
