### PR TITLE
Fixes #1437 : Adds Custom Color preview

### LINKED ISSUE #1437: changing the color picker in frontend
**I'm submitting a ...**
- [ ] bug report
- [X] feature request

Changing the color picker in the frontend to show the color picked

**I am sending a PR for the same**

### PR DESCRIPTION
**Pull request by gabru-md**
Fixes #1437 

#### Checklist

- [X] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [X] My branch is up-to-date with the Upstream `development` branch.
- [ ] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Adds a general color preview for the color picker

Cheers!
mmqw

### CODE REVIEW

**Comment by ParthS007** [comment]
Yes, Put that color `div` in the field itself.

**Comment by gabru-md** [comment]
mmqw
here are the new changes

**Comment by djmgit** [comment]
@gabru-md can you adjust the height of the color box equal to the height of the text box?
How will it look in that case? Any suggestons?

**Comment by gabru-md** [comment]
done @djmgit

**Pull request merged**
