### PR TITLE
Add overlay showing loading during generation of badges.

### LINKED ISSUE #574: Generate Badges taking time, so some indicator of loading/generating should be present.
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

After clicking on `Generate Badges`, there is no response for few seconds until badges are created message comes up.
**Expected behavior:**

Some indication of `loading ` in this time period.

**I am working on it **

### PR DESCRIPTION
**Pull request by rupav**
Fixes #574 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added necessary documentation (if appropriate)

### Preview Link 

- **Replace XXX with your PR no**
- Link to live demo: http://pr-575-fossasia-badgeyay.surge.sh  
Fixes #574 
#### Changes proposed in this pull request:

- Add overlay during generation of badges to indicate loading.

### CODE REVIEW

**Comment by rupav** [comment]
Done @abishekvashok

**Comment by abishekvashok** [comment]
Looks good, but I am seeing it infinitesimally. It's because of the wrong response as highlighted in an issue. We need to have error handling as well, as those are not related to this, approving.

**Comment by rupav** [comment]
@abishekvashok yes its not generating badges on surge. But with same locally, every time I am able to generate badges. Are you referring to https://github.com/fossasia/badgeyay/issues/571 ?

**Comment by abishekvashok** [comment]
@rupav yes it's #571

**Pull request merged**
