### PR TITLE
Code files,badges all are present in separate folders

### LINKED ISSUE #37: Uploads folder contain code files and created badges folders
**I'm submitting a ...**  (check one with "x")
- [x ] feature request
**Current behavior:**
 Uploads folder contains code files and created badges folder, which should not happen .

**Expected behavior:**
Uploads should only contain uploaded files and code files should be present in app/

### PR DESCRIPTION
**Pull request by nanspro**
Fixes #37 
#### Short description of what this resolves:
-Code is separated from static files.
-Proper directories arrangement

#### Changes proposed in this pull request:
-Uploads folder now only contains uploaded csv and png files.
-static/badges contain badges formed by uploaded files and also contains all-badges.pdf,all badgeszip,all svg zip.
-generate-badges.py and merge_badges.sh are now present in app/.

### CODE REVIEW

**Comment by nanspro** [comment]
@niccokunzmann  i am not able to solve codacy errors is it necessary to solve them beacuse many were already there.
But my code is working 100% properly so can you review it.

**Comment by nanspro** [comment]
@niccokunzmann  can you review my PR 
This time it passed codacy/pr.

**Comment by nanspro** [comment]
@jajodiaraghav

**Comment by nanspro** [comment]
@niccokunzmann  @jajodiaraghav  thanks for helping me this was my first major PR, i learned lot of things and i am more interested in open source now.

**Comment by jajodiaraghav** [comment]
Hi @nanspro You did great work. I would just like to advice you something. Whenever making changes to a file, always keep the code structure similar to the code already present. For instance, The file generate_badges has `var a = 5` (Notice the space before and after =)
Do not put it as `var a=5`

Anyway, Great work!

**Pull request merged**
