### PR TITLE
FIX #2077 :  Removes blank lines

### LINKED ISSUE #2077: Many blank lines and blank spaces in our code files
I have noticed many files containing blank spaces and blank lines which have no use and makes the code look bad. 
This will be a parent issue If anyone finds such occurrence fix them and submit the PR

### PR DESCRIPTION
**Pull request by geetchoudhary**
Remove blank lines

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by geetchoudhary** [comment]
@kushthedude , PTAL. 😄

**Comment by kushthedude** [comment]
Change the name neither it fixes indents nor spaces, just state removing blank lines

**Comment by kushthedude** [comment]
Also dont refer it to the issue, the issue also mention about indents which are uneven

**Comment by geetchoudhary** [comment]
> Also dont refer it to the issue, the issue also mention about indents which are uneven

done.

**Comment by geetchoudhary** [comment]
> Change the name neither it fixes indents nor spaces, just state removing blank lines

done.

**Pull request merged**
