### PR TITLE
Removing Optional Label from Uploading a png file and selecting image from dropdown

### LINKED ISSUE #201: Remove optional tag from "Upload PNG as background"
**I'm submitting a ...**
- [X] bug report
- [ ] feature request

**Current behavior:**

Since now we have to upload a PNG ( or choose from the dropdown ) therefore the optional tag must be removed from it.

pn

**Expected behavior:**

the OPTIONAL tag must be removed from "UPLOAD PNG AS BACKGROUND" 

**Yes I will do this**

### PR DESCRIPTION
**Pull request by nanspro**
Fixes #201 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

-Removing span of Optional label

### CODE REVIEW

**Comment by nanspro** [comment]
workspace 1_036

**Comment by nanspro** [comment]
@gabru-md  i believe we should remove optional label from dropdown also just like we did in "Enter data manually"

**Comment by gabru-md** [comment]
@nanspro it would be better to claim the issue. Because i was already working on it. Anyways thanks !

**Comment by nanspro** [comment]
@gabru-md  there was no one assigned to the issue when i opened it.
Anyway please self assign yourself next time so that others will know.

**Pull request merged**
