### PR TITLE
Added config for automatic heroku build

### LINKED ISSUE #247: Deploy on Heroku through Travis-CI
**I'm submitting a ...**
- [ ] bug report
- [X] feature request

**Current behavior:**
Only manual deployment is possible.

**Expected behavior:**
After successful travis build deploy to heroku 

**Would you like to work on this?**
yes

### PR DESCRIPTION
**Pull request by vaibhavsingh97**
Fixes #247 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:
- Added config to deploy automatically to heroku with each PR

### CODE REVIEW

**Comment by vaibhavsingh97** [comment]
@S2606 Currently Heroku is down in US region and also pipeline needs to be created in order to review apps through heroku

**Comment by meets2tarun** [comment]
Which purpose is it solving? @vaibhavsingh97

**Comment by vaibhavsingh97** [comment]
@meets2tarun please check issue #247

**Comment by meets2tarun** [comment]
I already found that in the PR description, this PR may also solve https://github.com/fossasia/badgeyay/issues/61
And how much progress you get into your forked repo?

**Comment by vaibhavsingh97** [comment]
@meets2tarun Actually, I amnot able to verify as Heroku is down from morning

**Comment by vaibhavsingh97** [comment]
@S2606 Can you please make me the owner of heroku deployment so that i can add ncessary configuration to make this PR work?

**Comment by meets2tarun** [comment]
Any progress?

**Comment by vaibhavsingh97** [comment]
@meets2tarun This PR works only if if add pipeline in Heroku and only owner can do that so i requested @mariobehling to make me owner but it seems that he is busy. So waiting for it 😄

**Comment by vaibhavsingh97** [comment]
@S2606 @meets2tarun I think after merging the PR we can check the automatic deployement. As of now, i am not able to

**Comment by mariobehling** [comment]
Please test this after the merge. Thanks!

**Pull request merged**
