### PR TITLE
Fixes #1231 : Adds sitemap to badgeyay frontend

### LINKED ISSUE #1231: Adding sitemap in badgeyay frontend
**I'm submitting a ...**
- [ ] bug report
- [X] feature request

Adding sitemap for badgeyay.

**I am working on this issue**

### PR DESCRIPTION
**Pull request by gabru-md**
Fixes #1231 

#### Checklist

- [X] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [X] My branch is up-to-date with the Upstream `development` branch.
- [ ] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Adds sitemap to badgeyay frontend

Cheers!

### CODE REVIEW

**Comment by gabru-md** [comment]
Imgur

**Comment by djmgit** [comment]
@gabru-md please check codacy.

**Comment by gabru-md** [comment]
@djmgit the file does ends with a new trailing line. I cannot understand as to why codacy is failing. I've pushed around 5 commits trying to fix it. Then I just squashed them all.

**Comment by gabru-md** [comment]
@djmgit I've again tried every fix possible, opening them in different IDEs to make sure that it is not caused by one IDE. but there is some problem with codacy. Can we just ignore it?

**Pull request merged**
