### PR TITLE
Fixes #1031 : Added Token service for validating request from frontend

### LINKED ISSUE #1031: Create service for adding Token in the header to validate the request in API
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behaviour:**

There is no authentication token being sent in the header of the request. To validate the request and we have to explicitly send the UID for each request to validate the user.

**Expected behaviour:**

There should be a token to authenticate the user request on the backend side. This will ease out the logic as we only have to send the data that is relevance to the request.

__Yes__ working on the same

### PR DESCRIPTION
**Pull request by yashLadha**
Fixes #1031 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] I have added necessary documentation (if appropriate)

### Preview Link 

- **Replace XXX with your PR no**
- Link to live demo: http://pr-XXX-fossasia-badgeyay.surge.sh  

#### Changes proposed in this pull request:

- Added token to authenticated user in frontend and sending the token in the header to validate request.
-

### CODE REVIEW

**Comment by djmgit** [comment]
@yashLadha have a look at travis.

**Comment by yashLadha** [comment]
Done @djmgit :+1:

**Comment by yashLadha** [comment]
Please review @ParthS007

**Comment by gabru-md** [comment]
@djmgit can this be merged?

**Comment by yashLadha** [comment]
Please review @djmgit

**Pull request merged**
