### PR TITLE
Adds QR code support to backend

### LINKED ISSUE #2116: Add QR code support for backend
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Description :**

Add support for QR code on the back end.
Parent issue #1729

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by abishekvashok**
Fixes #2116

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

Adds qr code support for backend. An optional flag qr_code shall be
passed which specifies whether qr code support must be added to the
badges.

qr_code text shall be specified by the same parameter.

### CODE REVIEW

**Comment by kushthedude** [comment]
Not required, Why are you adding new functionalities when the website is broken ?
What our primary concern is making badgeyay alive, Cant you understand such simple facts.

**Comment by abishekvashok** [comment]
Yes I agree on that. Instead of saying that badgeyay is down I see that only some functionalities are down, we need to fix them one by one, following on the best practices it is imperative to develop features in parallel as the website is still testable. Does that mean all features should be stripped and new ones stalled? I don't see it that this pr should be removed and not be opened again.

**Comment by kushthedude** [comment]
Do you ever understand what I say, I closed it so that complete focus could be on making website live.
You need to read them again I suppose,why do you want a feature when the website is already down. Where will you use QR on your local machine?

**Comment by kushthedude** [comment]
But since you dont understand basic of devops, Let it remain open but for god's sake don't merge until badgeyay has underwent extensive testing and all the systems are working as they are meant to be

**Comment by kushthedude** [comment]
Reopen when #2119 is fixed

**Pull request closed without merging**
