### PR TITLE
Remove overlapping of footer

### LINKED ISSUE #63: UI bug on successful '/upload'
**I'm submitting a ...**  (check one with "x")
- [X] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/badgeyay

**Current behavior:**

by1

Footer overlaps the form whenever '/upload' is successful.
**Expected behavior:**

The footer must not overlap with the form.
It should stay either fixed on bottom or should be placed below the form everytime.

**Steps to reproduce:**

Changing some CSS would definitely do.
:D

### PR DESCRIPTION
**Pull request by jishnujayakumar**
Fixes #63 #88

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

- [ ] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:
Footer section of UI was overlapping with the form element after successful upload of data. This bug was removed.

#### Changes proposed in this pull request:
Just an addition of a class="navbar-static-bottom" to footer element removed the overlapping issue.

### CODE REVIEW

**Comment by niccokunzmann** [comment]
@jishnujayakumar There appear to be conflicts, now that na other PR was merged...

**Comment by jishnujayakumar** [comment]
I didn't understand.

**Comment by niccokunzmann** [comment]
grafik

**Comment by niccokunzmann** [comment]
You can merge the updated development branch into your branch. Then, this file will show the conflicts and you can edit it again, commit, push, ...

**Comment by Pk13055** [comment]
@jishnujayakumar Pull the upstream code and fix the conflicts in the `app/templates/index.html` file. Then `git add .` and `git commit --amend`, followed by `git push origin development`

**Comment by Pk13055** [comment]
I have fixed the conflicts as of #101

**Pull request closed without merging**
