### PR TITLE
 Fixes#342 Changes layout of Add Background to badges 

### LINKED ISSUE #342: Change text and order for section: Add Background with custom color
Change text and order as follows:
* First: Add Default Image -> Use background template
* Second: Add PNG file -> Add background image
* Third: Add Background with custom color -> Choose background colors

### PR DESCRIPTION
**Pull request by ParthS007**
Fixes #342 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

-  Changes layout of Add Background to badges 
-  [Deployment Link](https://lit-harbor-67991.herokuapp.com/)
image

### CODE REVIEW

**Comment by ParthS007** [comment]
@harshit98 @djmgit Please review

**Comment by vaibhavsingh97** [comment]
Merging 👍

**Comment by ParthS007** [comment]
@vaibhavsingh97 I have changed the order also. please see it once again

**Comment by vaibhavsingh97** [comment]
@ParthS007 You have to change text 
   - First: Add Default Image -> Use background template
   - Second: Add PNG file -> Add background image
   - Third: Add Background with custom color -> Choose background colors

**Comment by ParthS007** [comment]
image

**Comment by ParthS007** [comment]
what you are trying to say, I am not getting it!

**Comment by ParthS007** [comment]
This `->` is not be included

**Comment by djmgit** [comment]
@vaibhavsingh97 please review so that it can be merged :)

**Comment by vaibhavsingh97** [comment]
@djmgit Mario already reviewed and asked what I want to 😅

**Pull request closed without merging**
