### PR TITLE
Added Watermark to badges.

### LINKED ISSUE #1924: Adding Watermarks to Badges in free Mode Limited to 10 Badges
**I'm submitting a ...**
- [x] feature request

**Current behaviour:**

**Expected behaviour:**

**Steps to reproduce:**

**Screenshots**

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by Puranjay25**
Fixes #1924 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Added watermark to badges.
-

### Screenshots for the change

-
Screenshot from 2019-03-26 16-22-59

-

### CODE REVIEW

**Comment by Puranjay25** [comment]
@rajvaibhavdubey @sk9331657 when I try to download the badge..it's showing the following error.

**Comment by yashLadha** [comment]
Would be great if this is implemented from the backend side and not to be done using CSS on frontend @Puranjay25

**Comment by Puranjay25** [comment]
@yashLadha yes sir, got your point

**Comment by kushthedude** [comment]
@Puranjay25 please reopen when completed

**Pull request closed without merging**
