### PR TITLE
Corrected SUSI.AI logo in header template

### LINKED ISSUE #321: Correct SUSI Logo in header template
Logo of the susi is not appropriate

### PR DESCRIPTION
**Pull request by yashLadha**
Signed-off-by: yashLadha <201551061@iiitvadodara.ac.in>

Fixes #321 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Corrected the logo image for SUSI project in header template

### CODE REVIEW

**Comment by vaibhavsingh97** [comment]
@yashLadha Please create issue first before sending PR.

**Comment by yashLadha** [comment]
@vaibhavsingh97 :+1: Forgotted sorry!

**Comment by yashLadha** [comment]
screenshot

**Comment by yashLadha** [comment]
Sure :+1: @mariobehling

**Comment by yashLadha** [comment]
Done :+1: @mariobehling

**Comment by yashLadha** [comment]
screenshot

**Pull request merged**
