### PR TITLE
Fixes #727 : Adds email to User Model

### LINKED ISSUE #727: Add email as a field to User Model
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Yes I will work on this**

### PR DESCRIPTION
**Pull request by gabru-md**
Fixes #727 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] I have added necessary documentation (if appropriate)

### Preview Link 

- **Replace XXX with your PR no**
- Link to live demo: http://pr-XXX-fossasia-badgeyay.surge.sh  

#### Changes proposed in this pull request:

- Adds email to User Model in database

### CODE REVIEW

**Comment by aayusharora** [comment]
Looks good to me

**Comment by djmgit** [comment]
@gabru-md please resolve conflicts. Rebase your branch.

**Comment by djmgit** [comment]
@gabru-md we need to update the mailing system, there we have used username to send mail.

**Comment by gabru-md** [comment]
Okay @djmgit. I will create an issue and get it done as well.

**Pull request merged**
