### PR TITLE
Removes Stale files and Ignored vscode folder

### LINKED ISSUE #577: Remove stale files from backend
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

Stale files are present, they are unwanted and should be removed.

**Expected behavior:**

They are removed

**List of files (listing the directories, remove them!)**
These folders are present in `/backend/app/static/`. Please remove:
- [x] css
- [x] images
- [ ] js
- [ ] svgs

**Steps to reproduce:**
Go to the repository and see :)

### PR DESCRIPTION
**Pull request by ParthS007**
Fixes #577 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added necessary documentation (if appropriate)

### Preview Link 

- **Replace XXX with your PR no**
- Link to live demo: http://pr-XXX-fossasia-badgeyay.surge.sh  

#### Changes proposed in this pull request:

- Removes Stale files
- Updated `.gitignore` for `.vscode`

### CODE REVIEW

**Comment by gabru-md** [comment]
@vaibhavsingh97 why are you approving a PR before travis check is approved?

**Comment by vaibhavsingh97** [comment]
@gabru-md I looked files and seems ok to me, but I will take care.

**Comment by ParthS007** [comment]
@djmgit @gabru-md Please review :smiley:

**Comment by vaibhavsingh97** [comment]
@gabru-md can we merge?

**Comment by gabru-md** [comment]
Merge this ?

**Pull request merged**
