### PR TITLE
Tests added for the edit badge section

### LINKED ISSUE #2042: Add Tests for the edit badge component
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Description :**

Tests have not been added for the edit badge feature

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by rajvaibhavdubey**
Fixes #2042 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Route tests added
- Controller tests added

### CODE REVIEW

**Comment by yashLadha** [comment]
Also try to avoid such PR's as that they do not bring any positive change in functionality of project. Instead of such PR's to add blank test may be you can add module test for components. Hope you will takes this in a positive manner @rajvaibhavdubey

**Comment by rajvaibhavdubey** [comment]
@yashLadha Route tests for route checking was implemented only in this PR. Will add more tests soon.

**Comment by yashLadha** [comment]
Will this be any use currently. I know TDD is a good practice but we haven't implemented module tests, so what is the use case of implementing check for existence of route.

**Comment by rajvaibhavdubey** [comment]
@yashLadha Will try to implement module testing for sure, btw I just noticed all the test files are empty.

**Pull request closed without merging**
