### PR TITLE
Added firebase service

### LINKED ISSUE #1070: Firebase admin service in ember
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

As there is a lot of firebase config that is being used in the frontend as well as backend. So admin should also have the right to change the firebase config according to the choice from admin route. This can be done through using service for the same.

__Yes__ working on the same

### PR DESCRIPTION
**Pull request by yashLadha**
Fixes #1070

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ ] I have added necessary documentation (if appropriate)

### Preview Link 

- **Replace XXX with your PR no**
- Link to live demo: http://pr-XXX-fossasia-badgeyay.surge.sh  

#### Changes proposed in this pull request:

- added firebase service for admin to modify environment variables
-

### CODE REVIEW

**Comment by yashLadha** [comment]
Waiting for admin route to get merged so that I can show you the
screenshot. Else there will be lot of conflicts. 😅

**Comment by djmgit** [comment]
@yashLadha please resolve conflicts

**Comment by djmgit** [comment]
@yashLadha had closed it by mistake.

**Comment by yashLadha** [comment]
Ping @djmgit Can you please review it

**Comment by yashLadha** [comment]
Ping @gabru-md

**Pull request merged**
