### PR TITLE
Fixes #888 : Enhanced font when slider is dragged

### LINKED ISSUE #888: Enhance the font size slider
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**
The values are shown in different div presently.

**Expected behaviour:**
Pop up the value of size while sliding the slider.

### PR DESCRIPTION
**Pull request by abhi40308**
Fixes #888 : Enhancing the font when slider is dragged

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] I have added necessary documentation (if appropriate)

### Preview Link 

- **Replace XXX with your PR no**
- Link to live demo: http://pr-XXX-fossasia-badgeyay.surge.sh  

#### Changes proposed in this pull request:

- Enhanced font size of slider text when slider is dragged
- Centered the slider text

### CODE REVIEW

**Comment by duttaditya18** [comment]
@abhi40308 Please fill the PR template correctly,

The Preview Link is : https://pr-897-fossasia-badgeyay.surge.sh/

**Comment by abhi40308** [comment]
@djmgit @ParthS007 @yashLadha  Please review, I've made the suggested changes but still codacy is failing.

**Comment by gabru-md** [comment]
@abhi40308 `footer.scss` needs to end with a new line.
please make the changes so that codacy passes and this can be merged.
:+1:

**Comment by abhi40308** [comment]
I have already added a newline in footer.scss , still failing @ParthS007 @gabru-md  : 
screen shot 2018-06-01 at 11 03 25 pm

**Comment by abhi40308** [comment]
@ParthS007 I already did it a few times, making minor changes and rerunning, i think it is a bug in codacy maybe. Will try again :)

**Comment by yashLadha** [comment]
@djmgit can this be merged as it is needed for the font slider to work in frontend.

**Pull request merged**
