### PR TITLE
[WIP] add running app in travis

### LINKED ISSUE #149: Fix Travis tests
**I'm submitting a ...**
- [X] bug report

**Current behavior:**

Currently, travis is failing.
https://travis-ci.org/fossasia/badgeyay/builds/278248341?utm_source=github_status&utm_medium=notification

**Expected behavior:**

Travis should run all the tests #147 and succeed.

**Steps to reproduce:**

Please create a pull request to work on this issue and submit commits which fix the errors.

### PR DESCRIPTION
**Pull request by niccokunzmann**
Fixes #149 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- run app in background
-

### CODE REVIEW

**Comment by S2606** [comment]
@niccokunzmann Just wanted to know why do we need this?

**Comment by vaibhavsingh97** [comment]
@S2606 Please resolve this
```
Traceback (most recent call last):

  File "main.py", line 1, in <module>

    from flask import Flask, render_template, request, redirect, url_for, flash

ImportError: No module named flask
```

**Comment by niccokunzmann** [comment]
@S2606 These tests fail: https://travis-ci.org/fossasia/badgeyay/builds/279855094#L566
and I do not thing other people have to resolve my issue for me and I do not want to wait for the tests running.

@vaibhavsingh97 Yes, I want to.

**Comment by niccokunzmann** [comment]
Currently, there is a test running but somehow, I do not see progress: 
https://travis-ci.org/fossasia/badgeyay/builds/279915800#L607

**Comment by vaibhavsingh97** [comment]
@niccokunzmann It's happening woth me also, it's in infinite loop

**Comment by niccokunzmann** [comment]
I do not see me working on this right now, closing.

**Pull request closed without merging**
