### PR TITLE
Fixes #895 : Extending APIError class for errors in frontend.

### PR DESCRIPTION
**Pull request by yashLadha**
Fixes #895

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] I have added necessary documentation (if appropriate)

### Preview Link 

- **Replace XXX with your PR no**
- Link to live demo: http://pr-XXX-fossasia-badgeyay.surge.sh  

#### Changes proposed in this pull request:

- Extended API Error class to provide errors in frontend.
-
screenshot from 2018-05-27 13-19-03

screenshot from 2018-05-27 13-18-43

### CODE REVIEW

**Comment by yashLadha** [comment]
Ping @djmgit please merge it

**Comment by djmgit** [comment]
@yashLadha please resolve conflicts.

**Comment by gabru-md** [comment]
close this? as the PR that was an extension got merged first

**Comment by ParthS007** [comment]
ok closing this :+1:

**Pull request closed without merging**
