### PR TITLE
Rectified issues in generate_badges.py

### PR DESCRIPTION
**Pull request by devshiva619**
Relates to #135 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Changed `from xml import etree` to `from defusedxml.lxml import etree` [`Link`](https://pypi.python.org/pypi/defusedxml#defusedxml-lxml)
- Changed `except Excetion: pass` to `except Exception: traceback.print_exc()`

### CODE REVIEW

**Comment by rupav** [comment]
@devshiva619 I am pretty much sure, defusedxml.lxml dont have 'etree' . 
please try importing in your terminal.

**Comment by devshiva619** [comment]
@rupav yes you are correct, I will rectify that :sweat_smile:

**Comment by rupav** [comment]
@devshiva619 I checked about this too during my  [PR213](https://github.com/fossasia/badgeyay/pull/213).
I dont think there is an alternative for this but you can try looking :) .
defusedxml.lxml.parse is what all was needed(refer my PR). 
Thanks :)

**Comment by devshiva619** [comment]
@rupav Thanks for help :+1:  you can have a look now, I was trying to delete the previous commit and deleted it from my local and then I made a new commit and pushed it but I can still see the deleted commit in my forked repo though it is deleted form my local.

**Comment by rupav** [comment]
Actually by deleting that, you made another commit, what you could have done was resetting rather .
( git reset 'commit id') 
Please Wait for maintainers to respond.
@S2606 should squashing commits into 1 in this case suitable ?

**Comment by devshiva619** [comment]
@rupan thanks. Sorry @S2606 I increased your work. I will keep that in mind in future.

**Comment by devshiva619** [comment]
@rupav is it correct now?

**Comment by mariobehling** [comment]
Please help to fix Travis in following PRs.

**Pull request merged**
