### PR TITLE
List alligned to left

### PR DESCRIPTION
**Pull request by vaibhavmatta**
Fixes #

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

-
-

### Screenshots for the change

-
-

### CODE REVIEW

**Comment by vaibhavmatta** [comment]
@kushthedude

**Comment by vaibhavmatta** [comment]
@mariobehling

**Comment by vaibhavmatta** [comment]
@kushthedude Yes!

**Comment by abishekvashok** [comment]
Please match this with an open issue, and then please update the pr description. for more details please read on this long piece of text: https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/

**Comment by kushthedude** [comment]
@vaibhavmatta Update or close, @abishekvashok can you please help in reviewing it?

**Comment by abishekvashok** [comment]
Instead of using custom css make use of semantic ui classes.

**Comment by abishekvashok** [comment]
Instead of using custom css make use of semantic ui classes.

**Comment by kushthedude** [comment]
Stale

**Pull request closed without merging**
