### PR TITLE
Generates Badges for Manual data with preselected image

### LINKED ISSUE #314: Badges not generating from Manual data entry
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
pdf is not generating after giving input.

**Expected behavior:**
badges should be generated.

**Steps to reproduce:**
Enter data manually and generate pdf.

### PR DESCRIPTION
**Pull request by gabru-md**
Changed an `elif` to `if` so that if a predefined image is used the the CSV is also checked for.
The error was caused because of the fact that `elif` was not executed if the `if` of image was encountered.
I've managed it and fixed the bug.

Fixes #314 

#### Checklist

- [X] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [X] My branch is up-to-date with the Upstream `development` branch.
- [ ] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Changed the `elif` to `if`

### Why was the Bug caused?

The bug was caused due to the fact that the `elif` of csv field was not encountered if a pre-selected image was used as background. It was due to the fact that `elif` was used instead of `if`. I've made the necessary changes and it does work now.

### CODE REVIEW

**Comment by gabru-md** [comment]
Original Code :
```python
    if img != '':
        if(img == 'user_defined.png'):
            bg_color = request.form['bg_color']
            text_on_image = request.form['text_on_image']
            do_svg2png(img, 1, bg_color, text_on_image)
            filename = img + '.csv'

        filename = img + '.csv'
    # If the textbox is filled
    elif csv != '':
        check_csv = csv.splitlines()
        count_line = 0
        for check in check_csv:
            line = check.split(',')
            if len(line) == 4:
                count_line = count_line + 1
        if count_line == len(check_csv):
            filename = "default.png.csv"
            f = open(os.path.join(app.config['UPLOAD_FOLDER'], filename), "w+")
            f.write(csv)
            f.close()
        else:
            flash('Write Data in Correct format!', 'error')
            return redirect(url_for('index'))
```

If the `img` was found then the `csv` was not encountered due to the `elif`. Therefore this is the new changed code:
```python
    if img != '':
        if(img == 'user_defined.png'):
            bg_color = request.form['bg_color']
            text_on_image = request.form['text_on_image']
            do_svg2png(img, 1, bg_color, text_on_image)
            filename = img + '.csv'

        filename = img + '.csv'
    # If the textbox is filled
    if csv != '':
        check_csv = csv.splitlines()
        count_line = 0
        for check in check_csv:
            line = check.split(',')
            if len(line) == 4:
                count_line = count_line + 1
        if count_line == len(check_csv):
            filename = "default.png.csv"
            f = open(os.path.join(app.config['UPLOAD_FOLDER'], filename), "w+")
            f.write(csv)
            f.close()
        else:
            flash('Write Data in Correct format!', 'error')
            return redirect(url_for('index'))
```
Thanks! PS : @S2606 @vaibhavsingh97 @jajodiaraghav @mariobehling @ParthS007

**Comment by gabru-md** [comment]
@mariobehling  @ParthS007 @S2606 @djmgit @vaibhavsingh97 @jajodiaraghav Please Review again.

There was some problem with the code elsewhere. @ParthS007 pointed that there was another problem. I've solved it now. Please review

**Comment by djmgit** [comment]
badge

@gabru-md If I select a png image and enter some data manually then I am getting the error trace shown in the screen shot above. Please have a look.

**Comment by gabru-md** [comment]
@djmgit sure i will have a look into it.

**Comment by gabru-md** [comment]
There is some problem with this PR. I will create a new one for this issue.
Sorry for inconvenience

**Comment by djmgit** [comment]
@gabru-md Not a problem at all, please go ahead :+1:

**Pull request closed without merging**
