### PR TITLE
[WIP] Added Swagger UI

### LINKED ISSUE #437: Add Swagger UI
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**
Swagger UI is not present

**Expected behavior:**
As this PR: https://github.com/fossasia/badgeyay/commit/82d6fcd79b087ba96d6cf4c20c1d075ed50a9c97 merged  
We need to add Swagger UI. Swagger does a simple but very powerful thing: with a bit of additional annotations it generates the REST API descriptions (HTTP methods, path / query / form parameters, responses, HTTP error codes, ...) and even provides a simple web UI to play with REST calls to your APIs (not to mention that all this metadata is available over REST as well).

**Yes, I want to work on the issue**

### PR DESCRIPTION
**Pull request by vaibhavsingh97**
Fixes #437 

#### Checklist

- [ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ ] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

-
-

### CODE REVIEW

**Comment by vaibhavsingh97** [comment]
This is the structure for our backend which I had thought of to make the code more maintainable. he following directory tree shows where each part of the logic is located.
```
├── api                         #
│   ├── generate                #
│   │   ├── main.py             #
│   │   ├── endpoints           #  API namespaces and REST methods
│   │   ├── parsers.py          #  Argument parsers
│   │   ├──serializers.py       #  Output serializers
|   |   ├──other file            #
│   └── restplus.py             #  API bootstrap file
├── app.py                      #  Application bootstrap file
├── database                    #
│   └── models.py               #  Definition of SQLAlchemy models
├── db.sqlite                   #
└── settings.py                 #  Global app settings

```
Your views please
Cc: @harshit98 @ParthS007 @mariobehling @djmgit

**Comment by ParthS007** [comment]
Add unitests as well @vaibhavsingh97  👍

**Comment by gabru-md** [comment]
@vaibhavsingh97 can you please explain as to why are we choosing a SQL database and not No-SQL one? I'm just curious.
:)

**Comment by S2606** [comment]
Looks good to me!

**Pull request closed without merging**
