### PR TITLE
Fixes#562 Adds package-lock.json

### LINKED ISSUE #562: Add Package-lock.json to frontend
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**
Presently, there is no package-lock.json in the frontend.

**Expected behavior:**
It should be added to the frontend.

Working on it 👍

### PR DESCRIPTION
**Pull request by ParthS007**
Fixes #562 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

-  Adds package-lock.json
- This file is intended to serve various purposes:
   - Describe a single representation of a dependency tree such that teammates, deployments, and continuous integration are guaranteed to install exactly the same dependencies.
   - Provide a facility for users to "time-travel" to previous states of node_modules without having to commit the directory itself.
   - To facilitate greater visibility of tree changes through readable source control diffs.
   - And optimize the installation process by allowing npm to skip repeated metadata resolutions for previously-installed packages.

[Source](https://docs.npmjs.com/files/package-lock.json)

### CODE REVIEW

**Comment by vaibhavsingh97** [comment]
@abishekvashok can you explain me why we need to change `.gitignore`?

**Comment by vaibhavsingh97** [comment]
@ParthS007 yes, please remove `package.json` from `.gitignore`

**Comment by abishekvashok** [comment]
Here you go!

**Comment by abishekvashok** [comment]
@ParthS007 next time I expect an awesome ecommit message from u.

**Pull request merged**
