### PR TITLE
Fix 1805 Default collapsed Menu in Admin Section

### LINKED ISSUE #1805: Default collapsed Menu in Admin Section
**I'm submitting a ...**
- [x] feature request

**Current behaviour:**

screenshot from 2018-10-15 12-35-11

**Expected behaviour:**

Should be collapsed.

Will work on issue??

### PR DESCRIPTION
**Pull request by sk9331657**
Fixes #1805

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added necessary documentation (if appropriate)

ezgif com-video-to-gif 24

### CODE REVIEW

**Comment by sk9331657** [comment]
@ParthS007 Now using Semantic UI for this

**Comment by ParthS007** [comment]
@sk9331657 Add a screenshot.

**Comment by sk9331657** [comment]
Ok

**Comment by sk9331657** [comment]
ezgif com-video-to-gif 24

**Comment by sk9331657** [comment]
@yashLadha  @gabru-md  @ParthS007  Please review .

**Pull request merged**
