### PR TITLE
inhanced code readibility and quality partial fix for #135

### PR DESCRIPTION
**Pull request by lapmid**
Fixes #

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

-
-

### CODE REVIEW

**Comment by lapmid** [comment]
why it is not being merged

**Comment by jajodiaraghav** [comment]
@lapmid Can you please mention why you broke the css file? This file was a minified css of a thirdparty library we are using. The codacy fix was for the `!important` keyword.
Please see https://www.codacy.com/app/fossasia/badgeyay/issues/

This is not the right fix. In case you are stuck somewhere, head over to gitter to get your doubts cleared

**Comment by jajodiaraghav** [comment]
Also, Please fill the PR description properly.
Use `Fixes #ABC` in the description, not in the title.

**Comment by lapmid** [comment]
Ok i will retry it again may be i misunderstood the issue

**Comment by jajodiaraghav** [comment]
@lapmid Can you please close this PR?
Please confirm on #135 before working on the fix.

Thanks :)

**Comment by lapmid** [comment]
Ok

**Pull request closed without merging**
