### PR TITLE
Add test report

### LINKED ISSUE #119: Make travis run the UI tests
This is an issue for people who would like to learn basic quality assurance using tests for web applications.
**I'm submitting a ...**
- [X] bug report

**Current behavior:**

Currently, travis does not run the UI tests.
These are tests that click on the webpage of the application and make sure, certain uer/stories and work flows stay while we develop.

**Expected behavior:**

I would liketravis to run those tests.

- [ ] add the tests to travis
- [ ] see that they fail in your pull-request because firefox can not start because travis has no GUI
- [ ] install phantomJS, a browser for such purposes without GUI and create a central place to change the "driver" (see source code)

**Steps to reproduce:**

https://travis-ci.org/fossasia/badgeyay/builds/277071140#L563
Related: a discussion in #116

### PR DESCRIPTION
**Pull request by S2606**
Fixes #119 

#### Checklist

- [X] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [X] My branch is up-to-date with the Upstream `development` branch.
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by S2606** [comment]
@niccokunzmann @jajodiaraghav @gabru-md please review
@jajodiaraghav if PR is good could you please tell how to squash commits??

**Comment by S2606** [comment]
And bdw :- https://travis-ci.org/S2606/badgeyay?utm_source=email&utm_medium=notification

**Comment by jajodiaraghav** [comment]
To squash:
1. git rebase -i head~2
2. Replace pick with squash for second commit in the editor. Save and close
3. git push origin patch_report -f

From next time, use `git commit --amend --no-edit`. I think I have mentioned this before to you.

I have also instructed the squash steps in different PRs. It would be great if you could follow them later.
@S2606

**Comment by S2606** [comment]
@jajodiaraghav in travix CI cant use git --amend becoz it crashes the whole CI

**Comment by niccokunzmann** [comment]
I did a squash and merge using the github API.
Thanks for this pull request. Now, we can fix travis.

**Pull request merged**
