### PR TITLE
Rectified issues in file merge_badges.py

### PR DESCRIPTION
**Pull request by devshiva619**
Relates to #135 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Replaced os.system with subprocess.run
- Also removed unused variable `subdirs`

### CODE REVIEW

**Comment by vaibhavsingh97** [comment]
@devshiva619 Can you please squash your commits into one

**Comment by devshiva619** [comment]
@vaibhavsingh97 yeah was trying to do that but when I did `git pull upstream development` I forgot to add a comment. So when I ran `git rebase -i HEAD~3` there was no commit shown for `git pull upstream development` so I cant squash. 
Hope I was able to explain myself.

**Comment by jajodiaraghav** [comment]
@devshiva619 That doesn't makes any sense. You should've used `git pull upstream development --rebase` to rebase the remote on your local branch. You can still squash your commits pretty easily. Please learn to use git properly.

I leave it to other maintainers if they want to merge this or wait for you to squash.

**Comment by devshiva619** [comment]
@jajodiaraghav I did not use `git pull upstream development --rebase` I used `git pull upstream development`. I just followed the local.md file. 
Can you please help me with this?

**Comment by ParthS007** [comment]
@devshiva619  Please use the command `git pull upstream development --rebase ` and squash your commits as this is the time when you learn new things. You can refer to [https://git-scm.com/book/en/v2/Git-Branching-Rebasing](url) for more information.

**Comment by ParthS007** [comment]
@devshiva619 Please use the command git pull upstream development --rebase and squash your commits as this is the time when you learn new things. You can refer to https://git-scm.com/book/en/v2/Git-Branching-Rebasing for more information.

**Comment by devshiva619** [comment]
@jajodiaraghav please review it, I have squashed it now.

**Pull request merged**
