### PR TITLE
Fixes #1935: Adds initial code for stripe frontend

### LINKED ISSUE #1935: Implementing Stripe on Frontend
**I'm submitting a ...**

- [ ] feature request

**Current behaviour:**

**Expected behaviour:**

**Steps to reproduce:**

**Screenshots**

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by abishekvashok**
Fixes #1935 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:
Adds intial frontend code for stripe payment integration

This contains only initial code for frontend. After implementation in backend, a small change must be made which will together enable the payment

### CODE REVIEW

**Comment by abishekvashok** [comment]
This should be merged only after my other 2 prs get merged.

@mariobehling can you share a sample billing plan?

**Comment by abishekvashok** [comment]
> If you are going to introduce any functionality, First always make server ready and than add the FE Code. Its like you are rendering a blank field without any mapping.

It will be done - does it matter that this should be rejected? Or any changes be done here?

**Comment by kushthedude** [comment]
> > If you are going to introduce any functionality, First always make server ready and than add the FE Code. Its like you are rendering a blank field without any mapping.
> 
> It will be done - does it matter that this should be rejected? Or any changes be done here?

Simply speaking, Frontend is decided on server requirements what you are doing here is deciding server requirements from client side?
Thats not the proper way to implement any payment gateway.
Regarding the major changes of dependencies you made, I cant approve it since its breaking on my local and I have already shared reference with you.

**Comment by abishekvashok** [comment]
Closing it as large number of conflicts

**Pull request closed without merging**
