### PR TITLE
Implementing Different Font Color Selection

### LINKED ISSUE #1853: Implementing Font Color  Selection on FrontEnd
**I'm submitting a ...**
- [x] feature request

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by sk9331657**
Fixes #1853

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Implementing Different Font Color Selection

### CODE REVIEW

**Comment by sk9331657** [comment]
@ParthS007  @gabru-md  @mariobehling Please review

**Comment by sk9331657** [comment]
@fossasia/badgeyay-admins  Review this .

**Comment by sk9331657** [comment]
@mariobehling  Can you please review this one ?? This is one of the core features.

**Comment by sk9331657** [comment]
@ParthS007  @gabru-md  @yashLadha  Reviews ??

**Comment by sk9331657** [comment]
@gabru-md  OK I will deploy it,

**Comment by sk9331657** [comment]
@gabru-md  CAn I provide gif output for this ??

**Comment by sk9331657** [comment]
@ParthS007 No, I will fixing in other pr . I am checking the color picker component for this .

**Comment by sk9331657** [comment]
@fossasia/badgeyay-admins  Please review this feature.

**Comment by sk9331657** [comment]
@yashLadha  @ParthS007  @gabru-md Please review.

**Comment by sk9331657** [comment]
@ParthS007  @mariobehling  @hpdang  @yashLadha  @mariobehling  Please review.

**Comment by sk9331657** [comment]
@ParthS007  @yashLadha  @gabru-md  @fossasia/badgeyay-devs  Can you please review and merge this ??

**Comment by abishekvashok** [comment]
Thanks

**Pull request merged**
