### PR TITLE
Fix 1893 Retrieving  Badges in My Badges Section

### LINKED ISSUE #1893: My Badges Not retrieving badges other than first page
**I'm submitting a ...**
- [x] bug report

**Current behaviour:**

Only badges from first pages is showing up.
**Expected behaviour:**

Filtering should be done properly

**Would you like to work on the issue?**

Yes , I am working on it.

### PR DESCRIPTION
**Pull request by sk9331657**
Fixes #1893 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

ezgif com-video-to-gif 6

-Fix 1893 Retrieving  Badges in My Badges Section
### Screenshots for the change

-
-

### CODE REVIEW

**Comment by sk9331657** [comment]
@gabru-md  @ParthS007  Reviews??

**Comment by sk9331657** [comment]
@abishekvashok  This can also be review.

**Comment by sk9331657** [comment]
@yashLadha  Can you please review this one also.

**Comment by sk9331657** [comment]
@yashLadha  @abishekvashok  @mariobehling  Please review . :smile:

**Comment by sk9331657** [comment]
@gabru-md Please review this also.

**Comment by sk9331657** [comment]
@gabru-md @yashLadha  @ParthS007  Please review this one.

**Comment by sk9331657** [comment]
@abishekvashok  Please review.

**Comment by sk9331657** [comment]
@mariobehling  Done.

**Comment by mariobehling** [comment]
Please fix Travis.

**Comment by sk9331657** [comment]
@mariobehling  Finally Fixed.

**Comment by sk9331657** [comment]
@mariobehling Done.

**Comment by sk9331657** [comment]
@mariobehling  Please review and merge this also .

**Comment by sk9331657** [comment]
@mariobehling  Please look at this one also.

**Comment by YogeshSharma0201** [comment]
@sk9331657, this code was not properly tested i guess, Badge model also needs to be updated. Otherwise it gives this error:
`TypeError: 'font_color_1' is an invalid keyword argument for Badges`

**Comment by sk9331657** [comment]
@YogeshSharma0201  This error is resolved in #1960 .

**Pull request merged**
