### PR TITLE
Add Hound CI

### LINKED ISSUE #105: Add Hound CLI
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [X] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/badgeyay

This would help new contributors provide good pull request

### PR DESCRIPTION
**Pull request by S2606**
Fixes #105 & #80 

#### Checklist

- [X] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [X] My branch is up-to-date with the Upstream `development` branch.
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by jajodiaraghav** [comment]
Can we configure this for Javascript and css too?

**Comment by niccokunzmann** [comment]
I would like to wait until the issue is an issue and not a todo. @jajodiaraghav Your comment could go to the issue to specify further, what this should do. To me, this is not clear.

**Comment by jajodiaraghav** [comment]
@niccokunzmann I agree. We should first work on knocking down the open issues that require urgent addressing. This PR might make it difficult to contribute for new contributors.

@S2606 I saw that you have claimed some of the issues together. Please claim one issue at a time so that others can work on different issues and the progress in not blocked.

**Comment by S2606** [comment]
@niccokunzmann This CI is found out in many of FOSSAsia's project. After finding out what exactly this is about, it helps in maintaining your code style in your pull request.

@jajodiaraghav This can be configured for javascript.And regarding claiming issues, I will take care of it in future.Now i need your approval to merge this.

**Comment by S2606** [comment]
@jajodiaraghav @niccokunzmann I have solves the issue. Please review it

**Comment by jajodiaraghav** [comment]
This looks good to me! Although, Shagun should've fixed both issues in different PR.
No issues though, this can be merged :)
Good work Shagun 🚗

**Comment by S2606** [comment]
@jajodiaraghav Thank you and should I merge or somebody else is merging?

**Pull request merged**
