### PR TITLE
Improves local development setup instructions

### LINKED ISSUE #64: Review for installation setup steps
Check the installation steps on the docs folder and report any changes to be made .

### PR DESCRIPTION
**Pull request by palnabarun**
Fixes #64 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Adds virtualenv instructions
- Adds ideal dev workflow instructions

### CODE REVIEW

**Comment by S2606** [comment]
@palnabarun Good work! I just had a doubt. If contributor uses virtualenv, a new directory is created. How about you add instruction regarding adding the directory in .gtignore file

**Comment by palnabarun** [comment]
@S2606  I wrote the docs such that the contributor uses `virtualenvwrapper` which creates no directories under the project root. So, there is no need to have that in `.gitignore`

**Comment by S2606** [comment]
Thank you!

**Comment by palnabarun** [comment]
@S2606  Happy to help. Looking forward to more contributions.

**Pull request merged**
