### PR TITLE
Fixes 3#868: Added admin and superadmin User model

### LINKED ISSUE #868: Add option to superadmin and admin in User model
**Current behaviour:**
there is no option to create superadmin and admin

**Expected behaviour:**
There should be an option to create super admin and admin

**yes, i am working on this**

sub-issue of #841

### PR DESCRIPTION
**Pull request by vaibhavsingh97**
Fixes #868

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ ] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:
- Added admin and Superadmin model

### CODE REVIEW

**Comment by vaibhavsingh97** [comment]
Cc @djmgit @ParthS007 @gabru-md @yashLadha please review :)

**Comment by djmgit** [comment]
@gabru-md @ParthS007 @yashLadha please review.

**Comment by vaibhavsingh97** [comment]
@djmgit Super admin user is the most powerful user and has full access to the badgeyay configurations. Basically one can think of super admin as `root` account, and admin don't have full access but can help in administration things. I added fields like deleted_at, updated to get basic insights. Basically, Every action is logged in database

**Comment by djmgit** [comment]
@vaibhavsingh97 ok
@ParthS007 @gabru-md @yashLadha please express your views on this PR.

**Comment by djmgit** [comment]
ping @yashLadha @ParthS007 @gabru-md

**Comment by vaibhavsingh97** [comment]
@gabru-md @ParthS007 @yashLadha Can you please review this PR

**Comment by gabru-md** [comment]
This thing needs to be revised ina nother way.
@ParthS007 @djmgit please close this

**Pull request closed without merging**
