### PR TITLE
Fix #497: Deploy Backend to Heroku

### LINKED ISSUE #497: Deploy backend and front-end to heroku.
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

As the backend and front end were seperate we dont have heroku deployment for both

**Expected behavior:**

Front end and backend should be deploy ee to heroku. They must be two heroku apps.

So we need to:
- [ ] Deploy front-end to gh-pages
- [ ] Deploy backend to heroku
- [ ] Update the form action in the front-end to the heroku deployment url of the backend.

At the end we should get a running app that is alle to generate badges and provide all functionality that v1 supplies. (Code is already there)

Note: Proceed only after an admin like @mariobehling gives you a url for the front-end and backend to be on heroku. After deployment it will be better if the ownership is transferred to him as well.

### PR DESCRIPTION
**Pull request by S2606**
Fixes #497 

#### Checklist

- [X] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [X] My branch is up-to-date with the Upstream `development` branch.
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by S2606** [comment]
Url:- https://badgeyay-api.herokuapp.com/

**Comment by S2606** [comment]
Please review @abishekvashok @djmgit @ParthS007 @vaibhavsingh97 @gabru-md

**Comment by S2606** [comment]
I can try that @vaibhavsingh97

**Comment by S2606** [comment]
In that case starting point would be from main.py right??

**Comment by abishekvashok** [comment]
@vaibhavsingh97 since we treat the two apps as two repositories is that required?

**Comment by mariobehling** [comment]
@vaibhavsingh97 Can we merge this as work in progress and rather solve things step by step? No need to solve everything with one PR. It seems good to me as a step in the right direction.

**Comment by abishekvashok** [comment]
Lets merge this then!

**Comment by abishekvashok** [comment]
@S2606 thank you!

**Pull request merged**
