### PR TITLE
Modified Running locally in README.md

### PR DESCRIPTION
**Pull request by rahuldecoded**
Modified the running locally.
Fixes issue #187

### CODE REVIEW

**Comment by vaibhavsingh97** [comment]
@rahuldecoded It's better that one should first open issues and then fix the issue via PR 😄. Please follow [best practices](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/) 👍

**Comment by vaibhavsingh97** [comment]
At the moment what i think that we already have [Local Installation](https://github.com/fossasia/badgeyay/blob/development/docs/installation/local.md) so we don't need setting up locally in README file.
What's your opinion?
Cc: @jajodiaraghav @gabru-md @niccokunzmann

**Comment by gabru-md** [comment]
I agree with @vaibhavsingh97.
@rahuldecoded please check the local installation link provided by vaibhav.

**Comment by rahuldecoded** [comment]
@gabru-md @vaibhavsingh97 I've seen those links. What I personally think is Running locally don't have any use as compared to Local Installation. I think it should be removed from README.md .

**Comment by niccokunzmann** [comment]
We can move it to an other docs/installation section.

**Comment by niccokunzmann** [comment]
I will merge it, so we do not discuss too much.

**Pull request merged**
