### PR TITLE
Fixes #813 : Persisting user in the frontend

### LINKED ISSUE #813: Persisting user in frontend after successfull login
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behaviour:**

Users are able to login to the site and corresponding Firebase user object gets created.

**Expected behaviour:**

The user should be saved in the ember data so that it can be used to reference in other requests as well.

__Yes__ I am working on this

### PR DESCRIPTION
**Pull request by yashLadha**
Fixes #813 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] I have added necessary documentation (if appropriate)

### Preview Link 

- **Replace XXX with your PR no**
- Link to live demo: http://pr-XXX-fossasia-badgeyay.surge.sh  

#### Changes proposed in this pull request:

- Persisted user in the frontend ember
-
 Youtube Video to ease review : 
<a href='https://youtu.be/1RPVRhP6Edg'>

</a>

### CODE REVIEW

**Comment by yashLadha** [comment]
Ping @djmgit @ParthS007 @gabru-md @vaibhavsingh97  please review and merge it.

**Comment by djmgit** [comment]
@yashLadha please rebase your branch!

**Comment by yashLadha** [comment]
Done rebasing @mariobehling

**Comment by yashLadha** [comment]
Please merge @djmgit , done rebasing :+1:

**Pull request merged**
