### PR TITLE
update install instructions

### PR DESCRIPTION
**Pull request by Ananthavijay**
Fixes https://github.com/fossasia/badgeyay/issues/1713

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Updated install instructions for Vagrant installation

@ParthS007 @gabru-md  pls review and merge
Thanks,
Anantha Vijay.M

### CODE REVIEW

**Comment by ParthS007** [comment]
@Ananthavijay Please read #1664. There I have asked to open a separate Issue for each doc. Please do that and add screenshots which shows the installation process. Images containing logo of vagrant doesn't seems to make sense. Please do the suggested changes.

**Comment by Ananthavijay** [comment]
@ParthS007 Sorry. My pc will be fixed by this sunday. So will add the screenshots later. Merge it 
Thanks

**Comment by Ananthavijay** [comment]
@ParthS007 I will do it once when my pc is fixed. So pls merge this PR

**Comment by abishekvashok** [comment]
@Ananthavijay we can wait till then :)

**Comment by ParthS007** [comment]
@Ananthavijay I hope you can now add the screenshots and we can merge this PR.

**Comment by ParthS007** [comment]
@Ananthavijay Please update the status of the PR by today otherwise I have to close the PR so that others can work on it. :+1:

**Comment by Ananthavijay** [comment]
yep @ParthS007 close this PR. I couldnt make it

**Comment by ParthS007** [comment]
Closing it. :+1:

**Pull request closed without merging**
