### PR TITLE
Fixes#498 Rectify Travis CI as per new architecture

### LINKED ISSUE #498: Rectify Travis ci tests
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

Travis ci runs code intended for the old architecture.

**Expected behavior:**

It should support the uncoupled architecture. It should run tests for the front-end and backend on isolated instances.i.e, by making use of the **isolated** parallel builds.

### PR DESCRIPTION
**Pull request by ParthS007**
Fixes #498 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Rectify Travis CI as per new architecture
- Run tests for the front-end and backend on isolated instances in Travis CI.

### CODE REVIEW

**Comment by abishekvashok** [comment]
@ParthS007 I think it should be `py.test` instead of `pytest` for the coverage.

**Comment by abishekvashok** [comment]
@ParthS007 can you squash the commits down to a single meaning full commit that explain whats done. I can also squash and merge if you wish but the latter is more professional. What do you think?

**Comment by ParthS007** [comment]
@abishekvashok Please wait for 2 hours , I have classes now , will squash with a proper commit message .I hope you understand 👍

**Comment by abishekvashok** [comment]
Sure you are free to take all the time in the world @ParthS007 :)

**Comment by vaibhavsingh97** [comment]
Waiting for travis build, will approve :+1:

**Pull request merged**
