### PR TITLE
Use envparse to change config variables locally.

### LINKED ISSUE #1810: use envparse or other utility like in open-event instead of harcoded variables.
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behaviour:**

Currently before sending a PR, I have to switch back to `ENV=PROD` from `LOCAL`, making it hard for the development process. This can be cumbersome, if other variables are too set this way for my local setup, and needs to be reverted back to original for sending the PR.

**Expected behaviour:**

This can be avoided, if we use [envparse](https://github.com/rconradharris/envparse) to parse the environement variables. This way it will fetch the env variable that I have set locally on my PC, instead in the project. This is also a good practice as per one of the 12 principles of `12 factors app`.

@yashLadha @gabru-md @ParthS007 your views on this?

_I would like to work on this._

### PR DESCRIPTION
**Pull request by rupav**
Fixes #1810

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

**envparse will first find if there exists an `.env file`, if not it will fallback to `environment variables` if set, if those too aren't set, `default values` will be set for those config variables.**

### CODE REVIEW

**Comment by rupav** [comment]
@gabru-md @ParthS007 @yashLadha please review.

**Comment by rupav** [comment]
@gabru-md made the changes in backend installations file.

**Comment by rupav** [comment]
@gabru-md now almost all config variables in config.py file can be set from .env file using envparse.
Added code for fetching `database` settings too - name, owner and password.
Added the corresponding instrunctions in installation instructions too.

**Comment by rupav** [comment]
@gabru-md please dont merge this now, I have one more think to add in it. - to read from file.

**Comment by rupav** [comment]
This can be merged now @gabru-md @ParthS007 @yashLadha

**Comment by gabru-md** [comment]
Thank you @rupav for reviewing the PRs as well.

**Comment by gabru-md** [comment]
Thank you @rupav for reviewing the PRs as well.

**Pull request merged**
