### PR TITLE
I want to resolve #172

### LINKED ISSUE #172: Add youtube video to README file
**I'm submitting a ...**
- [X] feature request

**Current behavior:**

There is a youtube video about badgeyay: https://www.youtube.com/watch?v=Gh8j_01LIoQ

**Expected behavior:**

People who are interested in the project should be able to check that out in order to 
get an overview about how it works.

**Steps to reproduce:**

- Edit the README file
- put the [video link](https://www.youtube.com/watch?v=Gh8j_01LIoQ) somewhere where new contributors expect it

The purpose of this issue is to make you familiar with the github collaboration process.

### PR DESCRIPTION
**Pull request by abhilash97**
Fixes #172

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

-
-

### CODE REVIEW

**Comment by pushkalkatara** [comment]
@abhilash97 Please squash your commits. For reference - https://www.devroom.io/2011/07/05/git-squash-your-latests-commits-into-one/ . If you face any difficulty, we are here to help :D

**Comment by vaibhavsingh97** [comment]
@abhilash97 Why you sent PR for the issue you already resolved?
Closing since, the issue is already resolved. 😃

**Comment by abhilash97** [comment]
@vaibhavsingh97  Sorry i wasn't clear about it actually. I had made done some changes so opened a pull request.

**Comment by abhilash97** [comment]
@pushkalkatara I squashed my commits going by the reference you provided, but am not sure of how to check if the changes have been done

**Pull request closed without merging**
