### PR TITLE
Fixes #1696 Add favicon.icon 

### LINKED ISSUE #1696: Add favicon on badgeyay papge
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behaviour:**
There is no favicon for badgeyay page
favbadge

**Expected behaviour:**

**Steps to reproduce:**

### PR DESCRIPTION
**Pull request by sk9331657**
Fixes #1696 

#### Checklist

- [x] have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.

### CODE REVIEW

**Comment by sk9331657** [comment]
@ParthS007  This can be now merged.

**Comment by sk9331657** [comment]
screenshot from 2018-09-14 21-43-44
I have added index icon of open event here , just for reference. This is screenshot . Please review  it. It didn't contained  extension adding extension created error.

**Comment by sk9331657** [comment]
@abishekvashok  Done Changes. :smile:

**Comment by sk9331657** [comment]
@abishekvashok @gabru-md  Please review it . :smiley:

**Comment by sk9331657** [comment]
@abishekvashok @gabru-md  Done Changes. :smile:

**Comment by abishekvashok** [comment]
Good job

**Comment by sk9331657** [comment]
@gabru-md  Please merge bro . :smile:

**Pull request merged**
