### PR TITLE
Fix the color-picker functionality

### LINKED ISSUE #244: Improve the function of "Color picker"
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

The color picker needs improvement. Also the "Enter text if user_defined" isn't automatically selecting the color as the user selects it.

### PR DESCRIPTION
**Pull request by jajodiaraghav**
Fixes #244

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- The color-picker was extremely buggy and poorly implemented. Several lines of unnecessary code was also merged which has been removed.

### CODE REVIEW

**Comment by vaibhavsingh97** [comment]
@jajodiaraghav Can you please share working link for the PR 😄

**Comment by jajodiaraghav** [comment]
@alirizwi Please see this PR for correct implementation of color-picker.

**Comment by jajodiaraghav** [comment]
@vaibhavsingh97 Asking for a working link would only shoo away contributors. Please review the code and merge.

**Comment by jajodiaraghav** [comment]
@S2606 @gabru-md Please review and merge so that I can continue my work

**Pull request merged**
