### PR TITLE
[WIP] Fix #149: Fix travis test for Travis

### LINKED ISSUE #149: Fix Travis tests
**I'm submitting a ...**
- [X] bug report

**Current behavior:**

Currently, travis is failing.
https://travis-ci.org/fossasia/badgeyay/builds/278248341?utm_source=github_status&utm_medium=notification

**Expected behavior:**

Travis should run all the tests #147 and succeed.

**Steps to reproduce:**

Please create a pull request to work on this issue and submit commits which fix the errors.

### PR DESCRIPTION
**Pull request by vaibhavsingh97**
Fixes #149 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by niccokunzmann** [comment]
I see you are installing phantomjs. Cool. Maybe, we also need to install and run selenium webdriver.

You can use #191 , too, if you like to use Python3.6 instead of Python 3.
The test runs but it times out: 
https://github.com/fossasia/badgeyay/pull/191/files#diff-354f30a63fb0907d4ad57269548329e3L1

**Comment by vaibhavsingh97** [comment]
@niccokunzmann I tried everything i can for Travis but i failed 😞 
In my laptop i am able to run tests on phantomJS but failing on Travis. can you please check what's wrong in travis config

**Comment by vaibhavsingh97** [comment]
@fossasia/badgeyay-admin Can someone help me to resolve the issue?

**Comment by vaibhavsingh97** [comment]
Closing Since, this PR not able to resolve Error

**Pull request closed without merging**
