### PR TITLE
Contact Us added in footer

### LINKED ISSUE #1939: Include Contact-us in the footer
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behaviour:**

Contact-us needs to be included in the footer

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by rajvaibhavdubey**
Fixes #1939

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Contact us has been added in the footer

#### Screenshots
screenshot from 2019-01-16 07-39-04

### CODE REVIEW

**Comment by mariobehling** [comment]
Thank you. Please provide a screenshot.

**Comment by rajvaibhavdubey** [comment]
@mariobehling Screenshots have been added in the PR description.
ThankYou :smile:

**Comment by rajvaibhavdubey** [comment]
@sk9331657, The footer was changed just before the addition of contact section.

**Comment by sk9331657** [comment]
> @sk9331657, The footer was changed just before the addition of contact section.

ok I will check .

**Pull request merged**
