### PR TITLE
Fixes #366: Added susper icon in the top right menu

### LINKED ISSUE #366: Adding icon linked to susper.com in the top right menu
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**
There is no icon of susper in the top right menu.

**Expected behavior:**
There should be a icon linked to susper.com in the top right menu.

**Would you like to work on this issue?**
Yes.

### PR DESCRIPTION
**Pull request by marvin08**
Fixes #366 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- I have added susper icon linked to susper.com in the top right menu.
- Here is the [demo link.](https://badgeyay2.herokuapp.com/)

screenshot from 2017-11-24 02 48 14

### CODE REVIEW

**Comment by marvin08** [comment]
@harshit98 @djmgit Please review.

**Comment by vaibhavsingh97** [comment]
@harshit98 Because of new changes made by @jajodiaraghav and test cases written are now outdated after the new changes. I opened the issue but before I solved it  @S2606 opened #368. After some minor changes his PR is ready to merge and will fix the Travis CI.
Thanks

**Comment by marvin08** [comment]
Ok @harshit98. I will do it.

**Comment by marvin08** [comment]
@harshit98 I have reduced the size of loklak icon. Please review this PR.

**Comment by mariobehling** [comment]
Thanks! Please help to fix the failing build now as well. Cheers.

**Pull request merged**
