### PR TITLE
app/generate-badges.py: Converts into a library

### LINKED ISSUE #379: GCI Task: Code refactor and updation
## Objective
Updating app/generate-badges.py so that it can be used as a library and can be imported from another file. At the same time provision should be kept for executing and running the file as a stand alone module so that the present system is not broken.

## Requirements
- A github account
- Knowledge of Git
- Basic knowledge of python.
- Clone the badgeyay repository
- Understand the code flow in generate-badges.py . 
- Create  a suitable issue for this task here.
- Create a new branch.
- Make changes.
- Add and commit your changes. Provide a suitable commit message.
- Send a pull request.

## Expected outcome
Submit a pull request with changes

### PR DESCRIPTION
**Pull request by abishekvashok**
Fixes #379 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:
Converts app/generate-badges.py into a library so that it can be
imported from another file and then be called using run_generator()
function.

Note: i have'nt figured out where it used.

### CODE REVIEW

**Comment by abishekvashok** [comment]
Any help on the failing tests @djmgit

**Comment by abishekvashok** [comment]
@djmgit I have implemented it, but still the tests are failing, any help would be appreciated.

**Comment by abishekvashok** [comment]
@djmgit sorry for pining you on and on, but I can't uderstand why the tests are failing even though I renamed it now :(

**Comment by abishekvashok** [comment]
@djmgit done :)

**Comment by abishekvashok** [comment]
Also note that, https://www.codacy.com/app/fossasia/badgeyay/pullRequest?prid=1183836 is failing only because I changed the name of the `generate-badges.py` (It sees it as an addition, and hence, states that lxml is vulnerable which was already vulnerable before this PR) :)

**Comment by abishekvashok** [comment]
Ping @fossasia/badgeyay-admins

**Comment by abishekvashok** [comment]
Sure

**Comment by abishekvashok** [comment]
Pls review @gabru-md @vaibhavsingh97 @S2606

**Comment by harshit98** [comment]
Good work! @abishekvashok

**Pull request merged**
