### PR TITLE
Showing Errors when png is not uploaded.

### LINKED ISSUE #138: No error shown when only csv file is uploaded
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
workspace 1_023
workspace 1_024

**Expected behavior:**
It should give an error like no png file found.

### PR DESCRIPTION
**Pull request by nanspro**
Fixes #138 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

-When image is not uploaded and csv file syntax is wrong(not .png.csv),i am showing error 'Please upload Csv file in \'.png.csv\' format'
-When image is not uploaded and csv file syntax is correct i am showing error "Please upload a image in png"

### CODE REVIEW

**Comment by nanspro** [comment]
workspace 1_025
workspace 1_026
workspace 1_027
workspace 1_028

**Comment by nanspro** [comment]
@jajodiaraghav  @gabru-md  can you review this.

**Comment by gabru-md** [comment]
@nanspro
Uploafing PNG image is optional so i believe that showing error is not a good idea.
Optional means that it is user's choice to wither input image or not. So if we generate an error on this point then it would be made compulsory for user to upload image.
@jajodiaraghav please comment.

**Comment by niccokunzmann** [comment]
This .png.csv format was a shortcut for me in the code. it could also have been speakers.csv instead of speakers.png.csv. You can say something like please opload a table in csv format: one line for each badge with commas

**Comment by niccokunzmann** [comment]
Thanks, so this is an improvement. That is why I merged it because of 
https://rfc.zeromq.org/spec:42/C4/ section 2.4, point 14 and 18 and because it can be improved soon.

**Pull request merged**
