### PR TITLE
Fixes #175 Adds GIF showing the working of badgeyay

### LINKED ISSUE #175: Readme Improvement
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

A minor fix in the [README.md](https://github.com/fossasia/badgeyay/blob/development/README.md) 

**Expected behavior:**

- [x] Branches are very important for a repository. Need of a section with an anchor link which describes the branch-policy. [link](https://github.com/fossasia/open-event-webapp#issue-and-branch-policy)
- [x] A section of describing the license of use-case of the repository under FOSSASIA. (link)(https://github.com/fossasia/open-event-webapp#license)
- [x] The technologies you are using in the repository and how it works [link](https://github.com/fossasia/meilix-generator#technologies-used).
- [x] Few people have slow internet connection so a gif include in the README.md is not a bad idea.
- [ ] A rule which includes updating the progress, so if the assignee is not updating the progress, other can carry out the job.

Look into the repository of which is the links are attached and further you can give your own idea and contribute.

**Steps to reproduce:**
NA

### PR DESCRIPTION
**Pull request by ParthS007**
Fixes #175 

#### Checklist

- [X] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [X] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Adds GIF showing the working of badgeyay
- It is helpful for all those who don't have a good Internet connection

### CODE REVIEW

**Comment by ParthS007** [comment]
@vaibhavsingh97 Yes we can remove the video link from the readme.

**Comment by ParthS007** [comment]
Can I remove it? @vaibhavsingh97

**Comment by vaibhavsingh97** [comment]
@ParthS007 Let's wait for others to input their opinion

**Comment by niccokunzmann** [comment]
Thanks for the image!

**Pull request merged**
