### PR TITLE
Fixes #797 : Added Google Cloud SDK for the backend

### LINKED ISSUE #797: Add Google Cloud SDK
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behaviour:**
Google Cloud SDK is not present

**Expected behaviour:**
To integrate Cloud SQL, Google Cloud SDK should be present in the system

**Yes, I am working on it**

### PR DESCRIPTION
**Pull request by yashLadha**
Fixes #797 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] I have added necessary documentation (if appropriate)

### Preview Link 

- **Replace XXX with your PR no**
- Link to live demo: http://pr-XXX-fossasia-badgeyay.surge.sh  

#### Changes proposed in this pull request:

- added google cloud sdk and the deployment of the backend on app-engine flex environment
- link : https://badgeyay-205003.appspot.com/

PS : If not working ping me to start the instance as it costs me to let them run :stuck_out_tongue:

### CODE REVIEW

**Comment by yashLadha** [comment]
Ping @djmgit @ParthS007 @gabru-md @vaibhavsingh97

**Comment by yashLadha** [comment]
__POSTMAN Testing__
screenshot from 2018-05-23 13-34-55

__Cloud Shell for PSQL Instance__
screenshot from 2018-05-23 13-45-47

__Entries Stored in DB__
screenshot from 2018-05-23 14-00-53

**Comment by djmgit** [comment]
@yashLadha codacy is showing 9 errors, are any of them solvable?

**Comment by yashLadha** [comment]
@djmgit Codacy is expecting to use `Maintainer` label but it is deprecated in the docs [Link](https://docs.docker.com/engine/reference/builder/#maintainer-deprecated). Also other Issues are related to passing the particular version number for dependencies but it is not necessary and not of priority to pass each dependency version. SO the PR is good to merge. Please review @ParthS007 @gabru-md @vaibhavsingh97 :+1:

**Comment by djmgit** [comment]
@yashLadha Nice work :+1: . Considering the fact that you have done GCP integration in an extremely short time and at almost one go, I am going with your PR. I hope everyone will accept this. Great work :+1:

**Pull request merged**
