### PR TITLE
Fixes#342 Changes layout of Add Background to badges and add responsiveness to info icon

### LINKED ISSUE #342: Change text and order for section: Add Background with custom color
Change text and order as follows:
* First: Add Default Image -> Use background template
* Second: Add PNG file -> Add background image
* Third: Add Background with custom color -> Choose background colors

### PR DESCRIPTION
**Pull request by ParthS007**
Fixes #342 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Changes layout of Add Background to badges
- [Deployment Link](https://pure-wildwood-76615.herokuapp.com/)
image

### CODE REVIEW

**Comment by ParthS007** [comment]
@S2606 It is there only .You can see the screenshot.
image

**Comment by ParthS007** [comment]
@S2606 will correct it in future PR, can you please check why Travis is failing.

**Comment by vaibhavsingh97** [comment]
@ParthS007  Opening new issue for travis Failing. @fossasia/badgeyay-devs Please be careful before merging the PR and makes sure TRAVIS don't fail. It's the responsibility of contributor to ensure to pass all the checks. Thanks

**Comment by ParthS007** [comment]
@vaibhavsingh97 I have done the requested changes and Travis is also failing in Previous PRs so I will create an issue for that :+1:

**Comment by ParthS007** [comment]
I have made an issue #392  for Travis fail, Please review @djmgit @harshit98 @S2606 @vaibhavsingh97

**Comment by vaibhavsingh97** [comment]
@ParthS007 You can use
```css
    position: absolute;
    top: 1%;
    right: 1%;
    font-size: 24px;
    border: 0;
```
and remove `!important`

**Comment by ParthS007** [comment]
@harshit98 @vaibhavsingh97 Please Review!

**Comment by ParthS007** [comment]
@harshit98 @djmgit @vaibhavsingh97 Please review!

**Comment by harshit98** [comment]
I'm merging this pull request as current improvements to the site. It needs more improvements in terms of responsiveness.

**Pull request merged**
