### PR TITLE
Fixes #1197 : Adds modifying permission for admin

### LINKED ISSUE #1197: admin api to manipulate permissions
**I'm submitting a ...**
- [ ] bug report
- [X] feature request

Adding backend api routes to manipulate the user permissions
**I am sending a PR for the same**

### PR DESCRIPTION
**Pull request by gabru-md**
Fixes #1197 

#### Checklist

- [X] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [X] My branch is up-to-date with the Upstream `development` branch.
- [ ] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Adds admin routes to modify permissions

An example screenshot is shared below

set_perm_admin

Cheers!

### CODE REVIEW

**Comment by gabru-md** [comment]
Ping @djmgit @ParthS007 @yashLadha

**Comment by ParthS007** [comment]
Please resolve conflicts :+1:

**Comment by gabru-md** [comment]
done @ParthS007

**Comment by gabru-md** [comment]
@yashLadha review please

**Comment by gabru-md** [comment]
@djmgit merge this?

**Pull request merged**
