### PR TITLE
Text color

### LINKED ISSUE #2020: Text Color Not Displayed in My Badges section
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Description :**
**Current behaviour:**

In badge description of badges in "My Badges" section Text Color is not displayed.

**Screenshots**

screenshot from 2019-03-01 17-33-28
**Would you like to work on the issue?**

Yes.

### PR DESCRIPTION
**Pull request by Puranjay25**
Fixes #2020

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

-In "My Badges" section "Text-color" field has it's value.

### CODE REVIEW

**Comment by rajvaibhavdubey** [comment]
@Puranjay25 I don't understand why do we need text_color, we already have font_color for the respective lines. Could you please explain. Thank you. :smile:

**Comment by rajvaibhavdubey** [comment]
@Puranjay25 I don't understand why do we need text_color, we already have font_color for the respective lines. Could you please explain. Thank you. :smile:

**Comment by Puranjay25** [comment]
@rajvaibhavdubey so you mean to say that in ny_badges.hbs we just need to replace {{badge.text_color}} with {{badge.font_color1}} ?

**Comment by mariobehling** [comment]
Closing this as unnecessary.

**Pull request closed without merging**
