### PR TITLE
Fixes Badge overlapping

### LINKED ISSUE #1947: Fix badge preview overlapping
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behaviour:**

The badge preview overlaps with the footer. 

**Screenshots**
screenshot from 2019-01-16 12-25-22

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by rajvaibhavdubey**
Fixes #1947

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Badge overlapping has been fixed by modifying the z-index.

### Screenshots for the change
screenshot from 2019-01-16 12-31-35

### CODE REVIEW

**Comment by sk9331657** [comment]
@rajvaibhavdubey  This patch is not working.

**Comment by rajvaibhavdubey** [comment]
@sk9331657 Can you please provide screenshot or tell the resolution at which it is not working. Because it seems fine to me.

**Comment by sk9331657** [comment]
Can you provide a gif for this ??

**Comment by sk9331657** [comment]
@rajvaibhavdubey  Show complete scrolling.

**Pull request merged**
