### PR TITLE
Fixes #2099: Updates outdated packages

### LINKED ISSUE #2099: update outdated dependencies on frontend
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Description :**

The many dependencies in the fronend are outdated

**Current behaviour:**

They are outdated

**Expected behaviour:**

They are upto date

**Steps to reproduce:**
Run `npm outdated`

**Would you like to work on the issue?**

Yes, on it

### PR DESCRIPTION
**Pull request by abishekvashok**
Fixes #2099

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

Updates outdated packages in front-end to new ones. Changed outdated code
to new syntax in most areas making project working.

### Screenshots for the change
Screenshot from 2019-08-14 18-09-38

### CODE REVIEW

**Comment by kushthedude** [comment]
Also, its one of the biggest change for FE, Can you please deploy it on Heroku or netlify, before merge?

**Comment by abishekvashok** [comment]
> Also, its one of the biggest change for FE, Can you please deploy it on Heroku or netlify, before merge?


See the screenshot

**Comment by abishekvashok** [comment]
> You also need to update the babel/parser

`npm outdated` returned nothing which means this is good to go. Maybe pull this branch and give a try :)

(Use the latest npm)

**Comment by kushthedude** [comment]
@abishekvashok Update your base branch to current head and see the errors.

**Comment by kushthedude** [comment]
image

Also, the deployment will fail, since the Heroku container and deployment variables are outdated too.

**Comment by abishekvashok** [comment]
> Also, the deployment will fail, since the Heroku container and deployment variables are outdated too

Are we continuously deploying now? - no. Please understand that we need to get things one by one in.

Run `ember serve` and see the website running down.

**Comment by abishekvashok** [comment]
> @abishekvashok Update your base branch to current head and see the errors

It is up to date (check my repo, 1 commit ahead), the head specs are good enough.  Try pulling my branch, put your head at the commit on this pr (ref is the same, head should be detached which is okay), and then after making sure npm and node are up to date, run:
`npm outdated` - will return nothing indicating that there are no outdated packages.

To ensure this doesn't break anything, please run the following code after making sure you have ember-cli and bower installed.
`npm install`
`bower install`
`ember serve`

This will fire up a website at localhost, visit it and make sure it works - it works for me and will work for you provided you do things as mentioned.

**Comment by kushthedude** [comment]
> image
> 
> Also, the deployment will fail, since the Heroku container and deployment variables are outdated too.

That was the output of ember serve and by heroku, I meant the website production deployment, Most of the changes are breaking and one more thing your Head is not pointed to current or you have not ran `npm install` after merging your head with `development` , 
There are a lot of `lint and import errors`
image

**Comment by kushthedude** [comment]
> > @abishekvashok Update your base branch to current head and see the errors
> 
> It is up to date (check my repo, 1 commit ahead), the head specs are good enough. Try pulling my branch, put your head at the commit on this pr (ref is the same, head should be detached which is okay), and then after making sure npm and node are up to date, run:
> `npm outdated` - will return nothing indicating that there are no outdated packages.
> 
> To ensure this doesn't break anything, please run the following code after making sure you have ember-cli and bower installed.
> `npm install`
> `bower install`
> `ember serve`
> 
> This will fire up a website at localhost, visit it and make sure it works - it works for me and will work for you provided you do things as mentioned.
> 
> _NB: the website will only load if you have backend running as well._

Give me a deployment link if you can work well, Cause in my local I am simply not able to `Login` after this, And a lot of warning has been increased cause the `CLI` is outdated and such change cant simply be made by `npm update` or any of the command you used to update dependency.

**Comment by abishekvashok** [comment]
Ignore lint errors as of now. I will provide the deployment link wait.

**Comment by kushthedude** [comment]
As you can see following errors are not lint, these are import errors.

**Comment by abishekvashok** [comment]
> As you can see following errors are not lint, these are import errors

Ember has migrated imports to a new syntax but the old one works - that is why lint errors occur.

**Comment by kushthedude** [comment]
Reopen after #2119 is fixed

**Pull request closed without merging**
