### PR TITLE
Fixex #1699 Badge Preview working perfectly Now for background color 

### LINKED ISSUE #1699: Preview not work profectly
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behaviour:**
when I select custom color for background then it's not showing in preview
badgeback

**Expected behaviour:**
It should be preview as it in default section

**Steps to reproduce:**

### PR DESCRIPTION
**Pull request by sk9331657**
Fixes #1699 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.

#### Changes proposed in this pull request:

-Setting background to one selected 
-Output 
## I have selected background color .

screenshot from 2018-09-15 00-14-26

## Now output is here:
screenshot from 2018-09-15 00-14-29

### CODE REVIEW

**Comment by gabru-md** [comment]
please try generating the badges using the background color and notice how it works maybe then you can make a change to [prreview functionality as well.

**Comment by sk9331657** [comment]
@gabru-md  I am not able to understand what actually is needed , like on changing the background color , the color of selected png needs to  be changed accordingly . Is that what is required??

**Comment by abishekvashok** [comment]
Exactly, but it should change when we select images as well!

**Comment by sk9331657** [comment]
Will open new one for this.

**Pull request closed without merging**
