### PR TITLE
Remove duplicate merge_badges.sh file

### LINKED ISSUE #16: Duplicate code
There are two merge_badges.sh files. Which one is the right one?
Please delete the one wich is not used.

### PR DESCRIPTION
**Pull request by S2606**
Fixes #16

### CODE REVIEW

**Comment by niccokunzmann** [comment]
Thanks!

**Comment by S2606** [comment]
You'r welcome @niccokunzmann

**Comment by jajodiaraghav** [comment]
@niccokunzmann This is not the right file. The Flask app is dependent on this file.
Please note that the Flask app resides inside "app" folder, and everything outside it can be removed. I didn't remove those files as I needed permission from Mario and you before doing so.

This PR broke the app.

**Comment by S2606** [comment]
@jajodiaraghav Should this PR be reverted or I create a new PR for this??

**Comment by jajodiaraghav** [comment]
Hi @S2606 I think we should should wait for Nicco's response. I don't think we need a new PR, Nicco can revert this PR directly.

**Comment by niccokunzmann** [comment]
@jajodiaraghav, please click on revert and create an other pull-request to establish the file.

**Comment by jajodiaraghav** [comment]
@niccokunzmann Already created a PR with the fix :)

**Comment by niccokunzmann** [comment]
Clicking on revert also creates a pull-request. If I generate it, I can not merge it, only after I  waited some time.

**Comment by jajodiaraghav** [comment]
The PR #24 fixes this problem. We do not need to revert this PR :)

**Pull request merged**
