### PR TITLE
Added menu and version

### LINKED ISSUE #6: Update the UI of the homepage
Currently UI of App Generator is lacking Menu item in header and Version deployment info in footer.

Expected behaviour:
Add menu like Google/Susper on the top right corner (http://susper.com/)
Add Version deployment info to the bottom like http://staging.loklak.org

Refer: https://github.com/fossasia/open-event-webapp/pull/1465

### PR DESCRIPTION
**Pull request by jajodiaraghav**
Fixes #6 
Screenshot:
screenshot from 2017-09-10 22-05-59

### CODE REVIEW

**Comment by mariobehling** [comment]
Thanks. Please keep the colors and style simple. Please use normal black on the top bar.

**Comment by niccokunzmann** [comment]
@jajodiaraghav Thanks for your PR. Do you own the rights on those files? Is it legal to put them under the MIT license? Please provide proof or claim that you created them. Otherwise it is illegal to use under the terms of the MIT license.
An alternative of which I do not know wether it is lawyer-proof, would be to add the license to the pictures i.e. in a README file.

**Comment by jajodiaraghav** [comment]
@niccokunzmann All the images used have been taken from this PR https://github.com/fossasia/open-event-webapp/pull/1465, which belongs to fossasia. I haven't created any image myself.
So do I have to create new images myself in order to get this merged? Some of them are logos of other applications such as loklak etc., Am I not allowed to use them ?

**Comment by niccokunzmann** [comment]
The images are under GPLv3. This project is under MIT. GPLv3 can include MIT code but not vice versa. Can you add the [GPL](https://github.com/fossasia/open-event-webapp/blob/development/LICENSE.md) license to the folder of the images? (only the images should go in in this folder) I am also fine with moving this project to GPLv3 or AGPL in general. If you are fine with this, too, you can change the license file to AGPL.

**Comment by niccokunzmann** [comment]
So, two solutions: 

1. move project to GPLv3/AGPL
2. add license for the images next to where the images are and make it obvious.

**Comment by jajodiaraghav** [comment]
That sounds good to me. Will add the license and change the color to black within a few hours :)
Thanks for the quick response.

**Comment by niccokunzmann** [comment]
An example, why this is important:
open event is under GPL. This means that if distributed, the code still needs to be changable by the user.
MIT would also allow to use the images in a propriatary, closed way. This is not intended by the person who created them. Thus, we should make it clear for the people using this service, that they can trust the license we provide.

**Comment by niccokunzmann** [comment]
Cool, thanks!

**Pull request merged**
