### PR TITLE
Fixed #1704 : Implemented Sticky Preview Functionality

### LINKED ISSUE #1704: Fixing the Preview Badge Position for Desktops,Pc
**I'm submitting a ...**
- [x] Feature request 

**Current behaviour:**

Currently  Badge is fixed to left 
screenshot from 2018-09-14 21-43-44

So when  user scrolls he doesn't come to know about changes in badge , user as to go up to see changes,  instead if position remains fixed for card then user  can view changes.

Currently :
screenshot from 2018-09-15 00-14-26

**Expected behaviour:**

Similar to  right div which will provide preview:

image9

### PR DESCRIPTION
**Pull request by sk9331657**
Fixes #1704  

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:
Working Demo :smile: 
ezgif com-video-to-gif 3

### CODE REVIEW

**Comment by sk9331657** [comment]
@ParthS007  @gabru-md  @abishekvashok  Please merge it. :smile:

**Comment by sk9331657** [comment]
@ParthS007  @abishekvashok  Please merge it . :smile:

**Comment by sk9331657** [comment]
@ParthS007  I have added the necessary script for working for fixing preview.

**Comment by ParthS007** [comment]
Please keep the commit message same as PR title.

**Comment by sk9331657** [comment]
@ParthS007  Done required Changes. :+1:

**Comment by sk9331657** [comment]
@ParthS007  This can be now merged.

**Comment by ParthS007** [comment]
ok @gabru-md, Let's go for it :+1: 
Merging it.

**Comment by sk9331657** [comment]
@ParthS007  Thanks . :+1:

**Pull request merged**
