### PR TITLE
Remove package-lock.json

### LINKED ISSUE #2148: Remove package-lock file from `FE` as we support yarn
Since we already added yarn, there is no need for the files generated by `npm install`

### PR DESCRIPTION
**Pull request by matheushf**
Fixes #2148 

#### Short description of what this resolves:
This removes package-lock.json

#### Changes proposed in this pull request:

- Removed package-lock.json

### CODE REVIEW

**Comment by matheushf** [comment]
Isn't the issue saying "remove package-lock.json"?

**Comment by kushthedude** [comment]
> Isn't the issue saying "remove package-lock.json"?

You need to remove `FE/Package-lock.json` only

**Comment by matheushf** [comment]
Done, although you might need more descriptive Issues

**Comment by kushthedude** [comment]
> Done, although you might need more descriptive Issues

I thought it was clear since I was referring to yarn and the obvious changes made using yarn is in FE.
ANYWAYS, squash the commit and correct the typo in the PR Heading.
Thanks

**Pull request merged**
