### PR TITLE
Fixes: #1757 , Displays info for email verification

### LINKED ISSUE #1757: Add a info for email-verification on create Badges
**I'm submitting a ...**
- [x] feature request

**Current behaviour:**

When the email of the user is not verified(local login) and he tries to create a badge, the create badge button gets disabled but nowhere is it displayed that the user must verify to continue.
**Expected behaviour:**

There should be a display of **Verify your Email address to continue**
**Steps to reproduce:**
-Login with username and password(local).
-Create badge without verifying email id.
-See the problem
verify

### PR DESCRIPTION
**Pull request by rajvaibhavdubey**
If the user's email address is not verified it displays an info for email
verification

Fixes #1757

Fixes #

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

-Displays info for email verification on local Login

screenshot from 2018-10-16 03-57-08

### CODE REVIEW

**Comment by ParthS007** [comment]
@rajvaibhavdubey Please update the PR. :+1:

**Comment by rajvaibhavdubey** [comment]
@yashLadha @ParthS007 The PR and the screenshots have been updated.
Thankyou :smile:

**Comment by ParthS007** [comment]
@rajvaibhavdubey Please check the other cards like updating User details in Admin. Follow the same design here.

**Comment by gabru-md** [comment]
maybe redirect the user from the page if the email is not verified and then show a notification just as we show in the login successful/signup successful types?
@ParthS007  @yashLadha views?

**Comment by rajvaibhavdubey** [comment]
@gabru-md Can u please explain me clearly the change requested :sweat_smile: , as I couldn't get it clearly

**Comment by gabru-md** [comment]
sorry for being so late. In case I'm unavailable please tag me on `gitter` so that I have a single notification on mail. 
I mean that can we have it in a way such that if the user is not verified then we can have the user redirected back to the home page maybe ? and then show a warning notification just like we show a successful notification when a user successfully log in or signs up for the system?

**Comment by ParthS007** [comment]
@rajvaibhavdubey PLease update the PR.

**Comment by rajvaibhavdubey** [comment]
@ParthS007 @gabru-md the PR and the screenshots have been updated, please have a review.
Thanks :smile:

**Comment by ParthS007** [comment]
@rajvaibhavdubey Please resolve Travis Issues else LGTM

**Pull request merged**
