### PR TITLE
Fixes#902 : Utility Function for changing User data

### LINKED ISSUE #902: Utility Function for changing User data
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**
The user cannot change its password or any other metadata.

**Expected behavior:**
There should be such utility that can be consumed by a route to provide this functionality

**Yes**, I am working on it.

### PR DESCRIPTION
**Pull request by ParthS007**
Fixes #902 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added necessary documentation (if appropriate)

### Preview Link 

- **Replace XXX with your PR no**
- Link to live demo: http://pr-906-fossasia-badgeyay.surge.sh  

#### Changes proposed in this pull request:

- Added Utility Function for changing User data.

### CODE REVIEW

**Comment by vaibhavsingh97** [comment]
Also, @ParthS007 I don't think so changing User data should come under Utility function. 
Cc @djmgit @gabru-md @yashLadha

**Comment by gabru-md** [comment]
@vaibhavsingh97 I guess it is okay to add it as a utility for the user.

**Comment by yashLadha** [comment]
As it is a helper functions and can be extended for consumption in routes as described in the issue, there is no reason to not put the function in utility.

**Comment by ParthS007** [comment]
Codacy is failing as we have three arguments for Error response but `pylint` wants only two. We already have many files like `file uploader` in which we have used Response class and have ignored these errors.
So This PR is good to merge :+1:

**Pull request merged**
