### PR TITLE
I want to resolve #172

### LINKED ISSUE #172: Add youtube video to README file
**I'm submitting a ...**
- [X] feature request

**Current behavior:**

There is a youtube video about badgeyay: https://www.youtube.com/watch?v=Gh8j_01LIoQ

**Expected behavior:**

People who are interested in the project should be able to check that out in order to 
get an overview about how it works.

**Steps to reproduce:**

- Edit the README file
- put the [video link](https://www.youtube.com/watch?v=Gh8j_01LIoQ) somewhere where new contributors expect it

The purpose of this issue is to make you familiar with the github collaboration process.

### PR DESCRIPTION
**Pull request by abhilash97**
Fixes #172

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

-
-

### CODE REVIEW

**Comment by rupav** [comment]
Hi @abhilash97 please edit you comment and write,
#172  so that Your PR get referred in that issue, and the issue can be closed. :)

**Comment by niccokunzmann** [comment]
@abhilash97 Welcome! Thanks for your pull request.
The pull-request looks good so far and we can close the issue after merging it.

Would you like to do one more edit and use the markdown syntax for links?
[source](https://guides.github.com/features/mastering-markdown/)

     [source](https://guides.github.com/features/mastering-markdown/)

**Comment by rupav** [comment]
Also to keep clean commit history, you should also squash your commits into 1. Refer this~
Use Git Command line interface:
'
$ git clone https://github.com/your/local/repo
$ git rebase -i HEAD~2
Change the 'pick' from one to 's'
Save the file 
$ git push origin development'

**Comment by niccokunzmann** [comment]
@rupav This is a first timer issue. Please be careful when proposing that someone must do something and consider that instead of one 100% all-time perfect pull request, you can have several small ones where the other person improves over time. The commits were made in the web editor and using the command line to do git magic seems to much to me for a first contribution.

**Comment by rupav** [comment]
ok @niccokunzmann. I will take care of it next time. 👍

**Comment by abhilash97** [comment]
@Yes i would love to do another edit, with markdown syntax.

**Comment by abhilash97** [comment]
@rupav , thanks for the information!

**Comment by rupav** [comment]
@abhilash97  Welcome to the community :)

**Comment by abhilash97** [comment]
@vaibhavsingh97 ,  thanks a lot!

**Comment by vaibhavsingh97** [comment]
@abhilash97 Can you please use thubmnail of project? As this is not relevant to the project.
P.S: Try clone the project locally and capture screenshot

**Comment by abhilash97** [comment]
@vaibhavsingh97  I did not get you completely.

**Comment by vaibhavsingh97** [comment]
@abhilash97 Please replace the image with this 
untitled design
Nit \ `To get a better idea about the working of badgeyay ,you can check out the following` add video after following

**Comment by niccokunzmann** [comment]
This is an improvement, thanks!

**Comment by niccokunzmann** [comment]
@abhilash97 Thanks for your pull request!

**Comment by niccokunzmann** [comment]
@vaibhavsingh97 @abhilash97 If you like to improve it further, you can do so. I believe, we should not wait until it is perfect, but show progress and let other people know as soon as possible, so I merged.

**Pull request merged**
