### PR TITLE
Change error message

### PR DESCRIPTION
**Pull request by niccokunzmann**
Fixes the uncertainties from #141

#### Checklist

- [X] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [X] My branch is up-to-date with the Upstream `development` branch.
- [X] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- the error messages make it clear to me, what to do and what is expected.
-

### CODE REVIEW

**Comment by niccokunzmann** [comment]
Because I did squash and merge, the commit by @nanspro turns up here. What would you like to use?
Squash & merge or better just merge or rebase & merge?

**Comment by jajodiaraghav** [comment]
@niccokunzmann I think you could just rebase followed by a forced push.
Also please fix the conflicts :)

**Comment by niccokunzmann** [comment]
So, I merged again.

**Comment by gabru-md** [comment]
@niccokunzmann try rebasing and squashing the commits if it is possible. Otherwise you may close the PR and make a new one with definite changes.
Okay?

**Pull request closed without merging**
