### PR TITLE
Updated dependencies of the backend and frontend

### LINKED ISSUE #686: Update dependencies of the backend and frontend
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**
Currently, there are many outdated dependencies in the project which needs to be updated including both frontend and backend.

I am working on this.

### PR DESCRIPTION
**Pull request by ParthS007**
Fixes #686 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Updated dependencies of the backend and frontend

### CODE REVIEW

**Comment by yashLadha** [comment]
@gabru-md for the development purpose still we need the dependencies to be in-place. If there is a case for new dependency then the same has to be added in his PR, else we all won't be able to test it locally.

**Comment by yashLadha** [comment]
The person who is adding new dependency in the system, its his responsibility to add the same in requirements else in the end we have to search to the error logs to find the dependencies. Hope you understand what i am pointing here @gabru-md

**Comment by gabru-md** [comment]
Okay

**Comment by ParthS007** [comment]
@yashLadha @gabru-md  Updated the PR :smiley:

**Comment by ParthS007** [comment]
@djmgit  Please review and merge :smiley:

**Pull request merged**
