### PR TITLE
Adds emberjs frontend

### PR DESCRIPTION
**Pull request by abishekvashok**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

Adds emberjs frontend designed by Abishek V Ashok
Live link: http://kindhearted-system.surge.sh/
screenshot_20180117_213015

### CODE REVIEW

**Comment by abishekvashok** [comment]
Pls discard builds, they are not intended for this PR!

**Comment by vaibhavsingh97** [comment]
@abishekvashok Good Job!! but these many files. Can you please clean?

**Comment by abishekvashok** [comment]
@vaibhavsingh97 these were generated with ember automatically and improve the functionality, eg) some minify css while some do js minification etc.

**Comment by abishekvashok** [comment]
@vaibhavsingh97 sorry, I see node_mouldes as well, clearing them.

**Comment by harshit98** [comment]
Yes @abishekvashok these are too many files.

**Comment by abishekvashok** [comment]
@vaibhavsingh97 @harshit98 done, pls review. I had commited the node_modules folder last time, removed it.

**Comment by abishekvashok** [comment]
@harshit98 thanks

**Comment by abishekvashok** [comment]
@ParthS007 thank you!

**Comment by vaibhavsingh97** [comment]
Merging, thanks for contributing 💯

**Comment by abishekvashok** [comment]
@vaubhavsingh97 thanks

**Pull request merged**
