### PR TITLE
Version 1: Ported to new branch

### LINKED ISSUE #657: Remove Version files to separate branch
As currently in the development branch `v1` is present and all the released versions should either be present in the master branch or in the respective version branch. What i am proposing is to remove the version folder from the development branch and shift it to either the master branch or version branch. So that the extra code gets cleaned and the code that is present in the branch will only get developed. Views @djmgit ?

Example: 

image

CC: @ParthS007 @vaibhavsingh97 @gabru-md

### PR DESCRIPTION
**Pull request by gabru-md**
Fixes #657 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ ] I have added necessary documentation (if appropriate)

### Preview Link 

- **Replace XXX with your PR no**
- Link to live demo: http://pr-XXX-fossasia-badgeyay.surge.sh  

#### Changes proposed in this pull request:

- Ports `v1` to Version 1.0 branch

### CODE REVIEW

**Comment by gabru-md** [comment]
It is due to the fact that the branch has the same `.travis.yml` as that of development but it does not have the same files as that of `development`. 
What should I do now @djmgit ?

**Comment by djmgit** [comment]
@gabru-md editing the v1 travis file should fix it right?

**Comment by gabru-md** [comment]
I've added a previous `.travis.yml` for the same.
@ParthS007 I might need some help in this one. :sweat_smile:  to configure travis again.

**Comment by djmgit** [comment]
Ignoring travis failure for this PR as travis always runs on the development branch.

**Pull request merged**
