### PR TITLE
Fixes #135

### LINKED ISSUE #135: Improve code quality (JavaScript or Python or Docker)
Currently, we can see [issues with the code](https://www.codacy.com/app/fossasia/badgeyay/issues)

We remove most of them! A clean code improves readability and speeds up development.

Please see the [issues with the code](https://www.codacy.com/app/fossasia/badgeyay/issues) and remove some of them. Create a separate pull-request for each file you change. In some cases, you may want to setup the project to check your changes work.

This is an issue with a lot of small tasks, so you can work in parallel or collaborate as you see fit.

### PR DESCRIPTION
**Pull request by toonarmycaptain**
Fixed typo in eventyayexport_anonymizer.py
Updated README

Fixes #

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Fixed typo "th" should be "the" in eventyayexport_anonymizer.py
- Made some updates to README to improve readability.

### CODE REVIEW

**Comment by vaibhavsingh97** [comment]
@toonarmycaptain Can you squash you commits and please use valid commit name.  TO know more about best practices ream more about it [here](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/)

**Comment by toonarmycaptain** [comment]
I changed the name right, I think. I can't get it to squash the commits :s I tried in bash following instructions, but it goes to a screen I can't move on from..

**Comment by toonarmycaptain** [comment]
I referred to that, followed the instructions. Saw what it said you would see. Reached second last step. GitBash doesn't let me proceed any further. I've tried troubleshooting, but can't find the issue/what II need to do there.

**Comment by jajodiaraghav** [comment]
@vaibhavsingh97 @ParthS007 I think toonarmycaptain is new to FOSS. We can be a little lenient for the first PR. Should we merge this and give him a chance to improve?

@toonarmycaptain Here are some tips from my side:
1. Please learn to use git properly. You have faced this issue because your concepts of git isn't clear. 
2. Use `git commit --amend --no-edit` to stack new changes to last commit.
3. Put proper titles of issues. "fixes #XYZ isn't right.
4. Write proper commit messages.

**Comment by vaibhavsingh97** [comment]
@toonarmycaptain Why you closed the pull request? It's better to ask and learn new things.

**Comment by toonarmycaptain** [comment]
Sorry - I hadn't found the git command jajodiaraghav shared. I'm preparing a new pull with just the typo fix, since the README has changed around since I last looked. I'll then read over that again and if I see improvements, create a separate pull for them. That's what I meant to do in the first place, but it added it.

**Pull request closed without merging**
