### PR TITLE
Revert "enh: Standardising Header Bar as of Open Event"

### LINKED ISSUE #2111: #2093 breaks frontend homepage
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Description :**

#2093 breaks the frontend home page on npm 5.6.x

**Current behaviour:**

#2093 breaks the frontend home page on npm 5.6.x

**Expected behaviour:**

It doesn't effect the frontend

**Steps to reproduce:**
Deploy the frontend

**Screenshots**

Screenshot from 2019-08-20 21-02-56

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by abishekvashok**
Reverts fossasia/badgeyay#2093

Fixes #2111

### CODE REVIEW

**Comment by kushthedude** [comment]
Revertnjg PR is not solution, go to the root and solve the problem causing it. First of all use the dependancies version specified in .json . 
Thanks.

**Comment by abishekvashok** [comment]
npm install uses them, copy pasting in the header bar from open event wasn't the solution in the first place.

**Comment by abishekvashok** [comment]
Self merging as it is very important

**Comment by kushthedude** [comment]
@abishekvashok did you even understand what I told you, such childish act is not expected , I told you to state the reason for error, for your concern There is a lot of difference of open event and badgeyay header. For once if you jad seen the projects correctly.
- 'npm install' uses them what is this , its only used yo installsemantic ui.
- Please for gods sake read once about ember and development lifecycle.
- Also if you want I can attach a link for semantic ui and how it works and changing class names dont function this way.
Also this is the second time you have done such act. If you dont know about something ping me , I will surely enlighten you, just making random reverts thinking would solve the problem is not the solution for anything.

**Pull request merged**
