### PR TITLE
Merge development into master

### PR DESCRIPTION
**Pull request by kushthedude**
Fixes #

#### Checklist

- [ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ ] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

-
-

### Screenshots for the change

-
-

### CODE REVIEW

**Comment by kushthedude** [comment]
@abishekvashok Do you have repository rights? Our master in not protected right now and PR settings need to be changed as branch should be up-to-date with base branch without merging.

**Comment by abishekvashok** [comment]
The question is do we require a merge now?

**Comment by kushthedude** [comment]
> The question is do we require a merge now?

Tts 2 years and not a single commit to master, Its now or never sort of thing, BadgeYay should be hosted on the master branch as done in every fossasia project

**Comment by kushthedude** [comment]
To be done after master has got its rights and repository rights are updated

**Pull request closed without merging**
