### PR TITLE
fixes #168 - fixes badges not found

### LINKED ISSUE #168: Badges not found
**I'm submitting a ...**
- [X] bug report
- [ ] feature request

**Current behavior:**
image
image

**Expected behavior:**
It should be downloaded!

### PR DESCRIPTION
**Pull request by djmgit**
Fixes issue #168, changed python to python3 in main.py - generate_badges
method. Badges are being generated now.

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by djmgit** [comment]
@niccokunzmann @S2606 this project used python3, in merge_badges.py python3 is checked as a dependency, however in generate_badges method in main.py uses python to execute merge_badges.py. It might be a problem if python3 is not default.

**Comment by jajodiaraghav** [comment]
@djmgit There is a conflict. Can you please fix it. 😄

**Comment by djmgit** [comment]
@jajodiaraghav yeah sure, I will fix it by tomorrow morning :)

**Comment by djmgit** [comment]
@jajodiaraghav resolved the conflicts

**Comment by jajodiaraghav** [comment]
Thanks @djmgit

**Pull request merged**
