### PR TITLE
Fixes#800: Added badge data in database

### LINKED ISSUE #800: Storing badge data in database
Now that, the badge generating logic has been integrated into the backend service, we can start with storing the badge data in database. So this issue requires creating any extra necessary models required and storing details in the db.

### PR DESCRIPTION
**Pull request by vaibhavsingh97**
Fixes #800

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:
- Added event logo, font, font size, font color, created at and updated at in model
- Saves generated badges

### CODE REVIEW

**Comment by djmgit** [comment]
@vaibhavsingh97 please rebase your branch.
Also please check the failing tests.

**Comment by vaibhavsingh97** [comment]
@djmgit Don't know what wrong with Travis, it sometime passes and sometimes fails. There is issue with Travis https://www.traviscistatus.com/.

**Comment by djmgit** [comment]
@vaibhavsingh97 still a lots of tests are failing, I would suggest, lets go forward with @gabru-md's PR for this same issue. I would suggest you to focus on admin and GCP integration rather than this one. There is no point in two people working on the same thing. I hope you understand.

**Comment by vaibhavsingh97** [comment]
closing https://github.com/fossasia/badgeyay/pull/819#issuecomment-390940634

**Pull request closed without merging**
