### PR TITLE
Fixed issue template

### PR DESCRIPTION
**Pull request by yashLadha**
Fixes : #702 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] I have added necessary documentation (if appropriate)

### Preview Link 

- **Replace XXX with your PR no**
- Link to live demo: http://pr-XXX-fossasia-badgeyay.surge.sh  

#### Changes proposed in this pull request:

- Fixes Issue Template
-

### CODE REVIEW

**Comment by yashLadha** [comment]
Updated @ParthS007

**Comment by vaibhavsingh97** [comment]
Nice!! So technically this is not an issue. nice catch Parth 😅

**Comment by yashLadha** [comment]
It is seen in the projects to use behaviour as the spelling and not
behavior as it is only reference in American English while other prefer to
use behaviour. So according to me behaviour is most apt. @gabru-md

**Comment by yashLadha** [comment]
Updated the commit message @gabru-md

**Comment by yashLadha** [comment]
As written in your link @gabru-md i also have stated the same. Please review again @ParthS007 @gabru-md

**Pull request merged**
