### PR TITLE
Fixes#369 Installation and Deployment Documntation

### LINKED ISSUE #369: Installation and Deployment Documntation
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**
Presently there is unmanaged documentation of installation and deployment

**Expected behavior:**
There should be proper directions for deployment and Installation so that new contributors don't find face any problem while deploying and Installing

Would you like to work on the issue?

YES

### PR DESCRIPTION
**Pull request by ParthS007**
Fixes #369 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Proper directions for deployment and Installation so that new contributors don't find face any problem while deploying and Installing

### CODE REVIEW

**Comment by harshit98** [comment]
@ParthS007 I would suggest some changes here:
- It would be better if you add an auto deploy feature using <a href="https://surge.sh/">Surge</a>. So that, each PR will be deployed automatically.
- Update the documentation as well.
- Example: <a href="https://github.com/fossasia/susper.com/issues/827">Check here</a>.
- After that:
    - Change PR name.
    - Change the issue name.

**Comment by ParthS007** [comment]
ok, @harshit98 I will do it by tomorrow. :+1:

**Comment by vaibhavsingh97** [comment]
@ParthS007 Also, Please reomve the Heroku automatic deployment code from travis as well.

**Comment by mariobehling** [comment]
Thanks.

**Pull request merged**
