### PR TITLE
feat: Added login logout functionality

### LINKED ISSUE #2175: Integrate Auth in Django [V-2.0]
**Is your feature request related to a problem? Please describe.**
Integrate Auth in Django
Parent issue #2168

### PR DESCRIPTION
**Pull request by codedsun**
Fixes #2175 

#### Short description of what this resolves:
Integrates auth flow for user

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by codedsun** [comment]
@iamareebjamal Please check and review

**Comment by kushthedude** [comment]
We are still not sure if we have to use template rendering or different frontend

**Comment by codedsun** [comment]
@kushthedude - @iamareebjamal asked me to use django auth for now, let see what he suggests.

**Comment by iamareebjamal** [comment]
Nevertheless we are going to have Django Auth anyway. And the last time we had a discussion, it was decided that we should go with Django templating as the project is not that UI intensive to use a separate frontend. Plus server side rendering is fast

**Comment by codedsun** [comment]
@iamareebjamal Yes, ok. Now please tell the next step what's to be done and also review this.

**Comment by iamareebjamal** [comment]
Override django user model

**Comment by codedsun** [comment]
@iamareebjamal Done

**Comment by iamareebjamal** [comment]
create migrations

**Comment by codedsun** [comment]
@iamareebjamal Done

**Review by iamareebjamal — APPROVED** [review]

**Comment by codedsun** [comment]
@iamareebjamal Thanks :)

**Comment by PragatiVerma18** [comment]
The v2 backend enables login but no signup. Can I fix the user authentication flow? Also, the Users model is not registered to admin.

**Pull request merged**
