### PR TITLE
Web UI for CSV upload

### PR DESCRIPTION
**Pull request by jajodiaraghav**
This PR presents a Flask based web UI so that users can upload a CSV file and download a PDF containing all the badges. The current implementation does not allow uploading a PNG alongside and the PNG options available are the ones already present in the repository.

We can work on adding more features to the UI once this gets merged.
In the meantime, Is it possible to host the application somewhere? (Heroku?)

Ping @mariobehling Waiting for your feedback

### CODE REVIEW

**Comment by niccokunzmann** [comment]
@jajodiaraghav For each question you have and for each improvement idea, please create an issue.

**Comment by niccokunzmann** [comment]
@mariobehling I think, @jajodiaraghav does great work. Can you add jajodiaraghav to the people with commit rights? Pull-Requests are still required but then it is possible for jajodiaraghav to guide others, too. I would do it myself if I had the rights to.

**Comment by jajodiaraghav** [comment]
@niccokunzmann Thanks a lot for the appreciation. I will open issues on each of the enhancement required.
I have a few more questions and it would be great if you could answer them
1. Why don't we have a dedicated chat stream to discuss about badgeyay? Currently it is merged with open-event-server
2. The main objective of the repository is to have a web UI for generating badges. The web app resides in /app folder. Can we remove the unnecessary files in root folder? This needs discussion

Thanks again

**Comment by mariobehling** [comment]
@jajodiaraghav We can have a dedicated channel. I tried to make one. There is an issue with gitter. Will be available soon. For the moment it is also good to involve people in the wider community. So, we added this topic to the existing open event channel.

**Pull request merged**
