### PR TITLE
Implemented Edit badge Functionality

### LINKED ISSUE #1665: Implement Edit badge Functionality
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**
Edit badge Functionality is not present in Backend and Frontend

**Expected behavior:**
The user should be able to edit the badge.

1. Please **open separate Issue** for respective Backend and Frontend Issue.
2. Please Provide the approach for the respective feature in the Issue.

### PR DESCRIPTION
**Pull request by YogeshSharma0201**
Fixes #1665

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Added a route /edit-badge/<badge_id>
- This route can be accessed by clicking on the edit icon on any badge in /my-badges
- Made changes in the backend db and fronted store for storing all the neccessary data.
- Added a controller for 'edit-badge' route which extends 'create-badges' controller and uses 'create-badges' template.

### Deployment Link:
[http://badgeyayedit.surge.sh](http://badgeyayedit.surge.sh/)

### Screenshots for the change

screenshot_20190304_185012

(Click on the edit icon to open /edit-badge page)

#### Edit Badges Page:

screenshot_20190304_185452

screenshot_20190304_185305

### CODE REVIEW

**Comment by YogeshSharma0201** [comment]
@gabru-md i have changed it to 'Save Changes' in latest commit.

**Comment by Puranjay25** [comment]
@YogeshSharma0201 could you help me with one part. How to add column in db. I added a column but when I run badgeyay, it shows column doesn't exists.

**Comment by YogeshSharma0201** [comment]
@Puranjay25 it's because database table doesn't have that yet, drop the table from the database and restart the app, this would create a new table with the updated column that you want.

**Comment by YogeshSharma0201** [comment]
@sk9331657 it was because of [this line](https://github.com/fossasia/badgeyay/blob/642962c1e279aac1135f40138bdc0090019fad2c/frontend/app/templates/create-badges.hbs#L9). I have fixed it.

**Pull request merged**
