### PR TITLE
Fix-1785 Adding Option to Simultaneously download multiple badges

### LINKED ISSUE #1785: Adding Option to Simultaneously download  multiple badges
**I'm submitting a ...**
- [x] feature request

Work on it ??
 Yes

### PR DESCRIPTION
**Pull request by sk9331657**
Fixes #1785 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Adding Option to Simultaneously download multiple badges
ezgif com-video-to-gif 23

### CODE REVIEW

**Comment by sk9331657** [comment]
@ParthS007  @gabru-md  Please review .

**Comment by sk9331657** [comment]
Yup . Will do by tonight .

**Comment by sk9331657** [comment]
@gabru-md  @sk9331657 Is this fine??
screenshot from 2018-10-21 12-35-25

**Comment by abishekvashok** [comment]
Instead of moving the download button down, move it up above the line.

**Comment by sk9331657** [comment]
It was already above line but @gabru-md suggested to place it to other position.

**Comment by abishekvashok** [comment]
The left align is fine, but if you could move it up the bar, at the same x coordinate, it would be great

**Comment by sk9331657** [comment]
@abishekvashok  Ok

**Comment by sk9331657** [comment]
screenshot from 2018-10-21 22-09-30
@abishekvashok  @gabru-md  Please review.

**Comment by sk9331657** [comment]
@yashLadha  @gabru-md  @ParthS007  Please review .

**Comment by sk9331657** [comment]
@ParthS007 Please review.

**Comment by sk9331657** [comment]
@gabru-md This can be merged.

**Pull request merged**
