### PR TITLE
Add sample Backgrounds.

### LINKED ISSUE #155: Use SVG image
**I'm submitting a ...**
- [X] feature request

**Current behavior:**

Currently, we can choose from a variety of badge backgrounds.
#152 introduced a new background picture.

**Expected behavior:**

Please allow an option to
- [x] (1) choose this background picture
- [x] (2) set the desired color
- [x] (3) set an image for the conference
- [x] (4) set a heading like "Speaker" or VIP

**Steps to reproduce:**

This is a multi-issue. If you like to work in it, please say, which part you like to work on.

### PR DESCRIPTION
**Pull request by rupav**
Fixes #155 checklist- 1,2 and 4.
Can be used for solving issue #153 4th.

Checklist

[ x] I have read the Contribution & Best practices Guide and my PR follows them.
[x ] My branch is up-to-date with the Upstream development branch.
[x ] I have added necessary documentation (if appropriate)
Changes proposed in this pull request:
#### Changes proposed in this pull request:
 
- main points(changes proposed) are --
-It extends the use of background with editable color, already done by me in #20.
-It includes background with 'FOSSASIA' logo on the top which is editable.
-Also it has a seperate file which have Heading too, like 'BUSINESS PASS' which is editable using a text editor.

Full report:
[Documentation for Use.docx](https://github.com/fossasia/badgeyay/files/1326641/Documentation.for.Use.docx)

### CODE REVIEW

**Comment by gabru-md** [comment]
@rupav Why do we have two PR for the same purpose?
PS : #165

**Comment by rupav** [comment]
@gabru-md  for 2 seperate files. Can it be done into 1 commit without adding a folder. I am new to this.

**Comment by gabru-md** [comment]
Use Git CLI:
```sh
$ git clone https://github.com/your/local/repo
$ git rebase -i HEAD~2
Change the 'pick' from one to 's'
Save the file 
$ git push origin development
```
and done

**Comment by rupav** [comment]
Done @gabru-md

**Comment by gabru-md** [comment]
@rupav I hope you understood.
Cheers!

**Comment by rupav** [comment]
Yeah. Sure thanks for help. Understood :)

**Pull request merged**
