### PR TITLE
QR code functionality

### PR DESCRIPTION
**Pull request by rajvaibhavdubey**
In process #1729

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

-The QR code has been added in the preview section, now it needs to be done
in the backend part( where the badge gets saved)

**Screenshots**
screenshot from 2018-10-20 00-05-30

### CODE REVIEW

**Comment by gabru-md** [comment]
This has been on hold for a long now can you please let us know what data is being stored into the QR code that you are applying to the image?


@rajvaibhavdubey

**Comment by rajvaibhavdubey** [comment]
@gabru-md Currently I am storing the firstname_emailid as a string in the qr code,however it can be changed in the future at any point of time.

**Comment by gabru-md** [comment]
please update @rajvaibhavdubey ?

**Comment by sk9331657** [comment]
@rajvaibhavdubey Please Update.

**Comment by yashLadha** [comment]
@rajvaibhavdubey Is the data encrypted ? This is because we can use the QR code for authentication at door scanner as well, and for that purpose they must be stored in a secure format.

**Comment by gabru-md** [comment]
Closing this PR since no further work is being done here.

**Pull request closed without merging**
