### PR TITLE
Fixes #1037 : Added verification mail

### LINKED ISSUE #1037: Email veriifcation on badgeyay
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behaviour:**

Currently firebase is taking care of the email verification part, with it's own link and doesn't allow to add custom domain in the verification link (only the names of the app and it's own custom url).

**Expected behaviour:**

As discussed in the previous meeting, URL should be of the website and for that we have to prepare the functionality in house. So creating the same.

__Yes__ working on the same.

### PR DESCRIPTION
**Pull request by yashLadha**
Fixes #1037

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] I have added necessary documentation (if appropriate)

### Preview Link 

- **Replace XXX with your PR no**
- Link to live demo: http://pr-XXX-fossasia-badgeyay.surge.sh  

#### Changes proposed in this pull request:

- Added verification mail as per discussed in the meeting
-

### CODE REVIEW

**Comment by djmgit** [comment]
@yashLadha please check travis failure.

**Comment by yashLadha** [comment]
As for the codacy errors the encryption and decryption only works best with md5 as we are performing encryption and decryption on two different languages using different libraries, so there internal structures are different for implementation of the same algorithm.

**Comment by yashLadha** [comment]
Please review @djmgit @ParthS007 @gabru-md

**Comment by gabru-md** [comment]
@yashLadha please look at the codacy error :D

**Comment by yashLadha** [comment]
@gabru-md I have mentioned that the libraries are working in sync with MD5 only and not with Sha...so that's why I have not changed it

**Pull request merged**
