### PR TITLE
Rectified errors in app/main.py

### PR DESCRIPTION
**Pull request by devshiva619**
Relates to #135 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Changed `os.system` to `subprocess.call`

### CODE REVIEW

**Comment by devshiva619** [comment]
I want ask one thing, I had previously sent PR in which the 1st three commits got  merged.
And as you can see I have made new PR the previously committed commits are also there.

**Comment by devshiva619** [comment]
codacy build failed because it gives errors for `import subprocess` `subprocess.call`

**Comment by devshiva619** [comment]
@jajodiaraghav @bhaveshAn sure I will do that. I wasn't well so I couldn't work, I will rectify this by tomorrow.

**Comment by mariobehling** [comment]
Closing this PR due to inactivity. Please make a new PR, if interested again. Cheers.

**Pull request closed without merging**
