### PR TITLE
Added a few new tests

### PR DESCRIPTION
**Pull request by jajodiaraghav**
Fixes #

#### Checklist

- [ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ ] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

-
-

### CODE REVIEW

**Comment by niccokunzmann** [comment]
@jajodiaraghav Who else would you like to see writing tests? You can ask this person to review, so you have a introductory conversation to the tests. I can read them but other people may not know how important tests can be or how to write them.

**Comment by jajodiaraghav** [comment]
Best would be to ping other contributors and see who would like to work on tests. What do you think?

**Comment by niccokunzmann** [comment]
Sounds good.

**Comment by jajodiaraghav** [comment]
@S2606 @gabru-md @nanspro @djmgit @pushkalkatara

**Comment by niccokunzmann** [comment]
@jajodiaraghav it seems the tests are not run, when I look at the development branch: https://travis-ci.org/fossasia/badgeyay/builds/276930731

**Comment by jajodiaraghav** [comment]
Yes I am aware of that, this is because Travis does not have a browser to fire off. I mentioned this when I integrated selenium.
I do not know how to fix this as I am using selenium for the first time.

**Comment by gabru-md** [comment]
@jajodiaraghav You can use phantomJS.
It is a HeadLess browser mostly used for testing purposes.

**Comment by niccokunzmann** [comment]
You can install the browser phantomjs and use the webdriver with phantomjs instead of firefox. That was it when I did it some time ago.

**Comment by niccokunzmann** [comment]
@jajodiaraghav @gabru-md This is a nice issue for someone who likes to get introduced to testing.

**Comment by niccokunzmann** [comment]
@S2606 You can also review this and merge... It tells you something about the tests.

**Pull request merged**
