### PR TITLE
Fixes #437: Added Swagger UI

### LINKED ISSUE #437: Add Swagger UI
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**
Swagger UI is not present

**Expected behavior:**
As this PR: https://github.com/fossasia/badgeyay/commit/82d6fcd79b087ba96d6cf4c20c1d075ed50a9c97 merged  
We need to add Swagger UI. Swagger does a simple but very powerful thing: with a bit of additional annotations it generates the REST API descriptions (HTTP methods, path / query / form parameters, responses, HTTP error codes, ...) and even provides a simple web UI to play with REST calls to your APIs (not to mention that all this metadata is available over REST as well).

**Yes, I want to work on the issue**

### PR DESCRIPTION
**Pull request by vaibhavsingh97**
Fixes #437 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:
- Automaticaly add documentation based on the schema declared in the function
- Documentation serves at: http://127.0.0.1:5000/apidocs/

Reference Screenshot:
image

image

image

### CODE REVIEW

**Comment by yashLadha** [comment]
As i can see there are two commits. Try to have single change done in one PR.

**Comment by yashLadha** [comment]
Please squash your commits

**Comment by yashLadha** [comment]
Please drop the commits that are not necessary to the PR.

**Comment by harshit98** [comment]
Hi @vaibhavsingh97 👋  what's the status of this PR? 

You're in GSoC phase and mentors are already aware that student must be aware of best practices. Please do follow them. Please note if you're doing other internship during GSoC phase and if you think that you'll not be able to contibute, you can feel free to withdraw from the program. Cheers! ✨

**Comment by vaibhavsingh97** [comment]
Something wrong with this branch, I am in the continuous loop. Still not able to rebase and squash. Will open new PR

**Pull request closed without merging**
