### PR TITLE
Disable Generate badges button

### LINKED ISSUE #336: Disable the Generate badges button unless required data is entered
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

Enabled button

**Expected behavior:**

Disabled "Generate badges" button unless required data is entered

Working on it

### PR DESCRIPTION
**Pull request by jajodiaraghav**
Fixes #336 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by jajodiaraghav** [comment]
Nice catch @djmgit Fixed 🛩

**Comment by jajodiaraghav** [comment]
@vaibhavsingh97 I have tried several times but I am unable to reproduce the issue.
@djmgit Are you able to reproduce this?

**Comment by jajodiaraghav** [comment]
@S2606 @ParthS007 @gabru-md Please see if you can reproduce the issue.

**Comment by vaibhavsingh97** [comment]
@jajodiaraghav 
Steps to Reproduce:
1. Add CSV
2. use `Add Background with custom color `
3. issue reporduced

**Comment by djmgit** [comment]
@vaibhavsingh97 you need to select a color

**Comment by vaibhavsingh97** [comment]
@djmgit I already selected color, and whatif i want to go with default color

**Comment by djmgit** [comment]
@vaibhavsingh97 @jajodiaraghav if user wants to use the colour then it can be a UX issue.

**Comment by gabru-md** [comment]
@djmgit can you olease explain how will it be a UX issue ?

**Comment by gabru-md** [comment]
I guess we can have a default value for custom color in the color box. So that this issue can be resolved ? 
What do you say @djmgit @jajodiaraghav?  @vaibhavsingh97

**Comment by jajodiaraghav** [comment]
@vaibhavsingh97 I have removed the default color. Now "whatif i want to go with default color" issue is eliminated. This was in no way related to my PR.
Anyway, Please check and merge @djmgit @gabru-md

**Comment by gabru-md** [comment]
Thanks!

**Pull request merged**
