### PR TITLE
Adds Plugins and setup for modularising frontend

### LINKED ISSUE #739: Add Plugins and setup for modularising frontend
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

There is a need to setup basic plugins for getting started to work on different components of the frontend.

Working on it.

### PR DESCRIPTION
**Pull request by ParthS007**
Fixes #739 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Added Plugins and setup for modularising frontend 
- Added Semantic UI, babel-eslint, ember-suave.

### CODE REVIEW

**Comment by aayusharora** [comment]
Hi @ParthS007 
Can you play attention to the Hound errors, some of them seems crucial.

**Comment by ParthS007** [comment]
Yes @aayusharora , I am working on resolving these errors :+1:

**Comment by ParthS007** [comment]
@aayusharora @djmgit @gabru-md @yashLadha @vaibhavsingh97  Please review :smiley:

**Comment by ParthS007** [comment]
@djmgit  Please review :smiley:

**Pull request merged**
