### PR TITLE
Added merge class to the library

### PR DESCRIPTION
**Pull request by yashLadha**
Fixes: #628

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] I have added necessary documentation (if appropriate)

### Preview Link 

- **Replace XXX with your PR no**
- Link to live demo: http://pr-XXX-fossasia-badgeyay.surge.sh  

#### Changes proposed in this pull request:

- Added the merge badges class to the library
-

### CODE REVIEW

**Comment by yashLadha** [comment]
Ping @djmgit @ParthS007 @gabru-md @vaibhavsingh97

**Comment by yashLadha** [comment]
Ping @djmgit @vaibhavsingh97 @ParthS007 @gabru-md

**Comment by yashLadha** [comment]
@djmgit Please review the package. I have ported it to the latest code.

**Comment by gabru-md** [comment]
@yashLadha I am still not convinced that why do we need a CLI package for same.
Because Badgeyay started as a CLI package and with time it became obsolete and was ported to a Web based project. Moreover, maintaining CLI as well as Web based product at once will prove hectic and the main aim of the project is to make it a complete web application.

@djmgit , @ParthS007  and @vaibhavsingh97 can you please comment on this?
If I am missing something here?

**Comment by yashLadha** [comment]
Actually it is not a CLI basically, it will be a PyPI Package which contains the functionalities (backend) and it can be extended to created new features in the core logic part. The code will get modularised as pointed by @djmgit  and the backend and frontend logic will get separated. I am talking of creating a CLI but instead a package and extend it in the web application backend. Hope it convinces you.

**Comment by yashLadha** [comment]
Please review @djmgit

**Comment by yashLadha** [comment]
@djmgit  @ParthS007 @gabru-md @vaibhavsingh97  The package is created as used as a module.

cli

**Comment by djmgit** [comment]
@yashLadha nice work, do we really require a separate pypi package now? I mean, what I was trying to say is separating the logic files, like merge_badges_class.py, exceptions.py, generate_badges.py, svg_2_png.py, etc to a separate package (like we normally do, moving all the files, to a folder, creating an __init__.py and importing the classes over there) That would have separated the core logic from the web logic.
So do we really need a pypi package for the entire badgeyay with a separate setup.py?

@gabru-md @yashLadha @ParthS007 @vaibhavsingh97 your views?

**Comment by yashLadha** [comment]
I am just proposing a approach, that is used in different projects. If you don't think it is worth the concern then we can drop the idea. What do you think? @djmgit

**Comment by gabru-md** [comment]
@djmgit I have the same doubt as yours. I do not know if we really need it or not.

**Pull request closed without merging**
