### PR TITLE
Adds .yaydoc.yml for automatic yaydoc generation

### LINKED ISSUE #382: Implement Yaydoc docs generation in badgeyay
Yaydoc is FOSSASIA's own automatic documentation generation and deployment project. At the crux of it, Yaydoc generates a documentation website using the markdown present in a project's repository and keeps the website in sync with the changes made in project's documentation.

The project requires a .yaydoc.yml configuration file at the project's root directory. Adding necessary information in the configuration file and registering the project at https://yaydoc.herokuapp.com/ will be enough to generate the documentation website.

**Objective:** Create the .yaydoc.yml file in the badgeyay repository and show preview Documentation website generated from the Yaydoc website.

**Expected Outcome:** Submit a pull request creating .yaydoc.yml file and a link to the preview page

**Links:** http://dev.yaydoc.org/user_manual/yaydoc_configuration.html

### PR DESCRIPTION
**Pull request by abishekvashok**
Fixes #382 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

Adds .yaydoc.yml for automatic yaydoc generation for each commit.

Link to Preview: https://yaydoc.herokuapp.com/preview/abhi2424shekvashok@gmail.com/d7476f1a-8a70-4a81-9cc1-b541ca97929b_preview/

### CODE REVIEW

**Comment by vaibhavsingh97** [comment]
@abishekvashok Preview link is not working
Reference:
image

**Comment by abishekvashok** [comment]
Pls try on this link: http://yaydoc.herokuapp.com/preview/abhi2424shekvashok@gmail.com/72e77b07-b348-4a1b-9b4e-010a583278bb_preview

**Comment by vaibhavsingh97** [comment]
@abishekvashok Getting same error

**Comment by abishekvashok** [comment]
@S2606 it's OKAY to include Fixes issue no: on the PR body as well. It closes the issue.

@vaibhavsingh97 I think it's being timed out again and again. Here's a new link, pls review it before it expires ;) 

image

Link: http://yaydoc.herokuapp.com/preview/abhi2424shekvashok@gmail.com/cfbdfe13-4ff6-411e-ac21-4c85c6356e0d_preview/

image

**Comment by abishekvashok** [comment]
@fossasia/badgeyay-admins 
Please ping me when someone of you come online, as I will give you a preview then, the preview links are always expiring within an hour. I have provided the preview screenshot, if it is enough please do a merge.

**Comment by harshit98** [comment]
@abishekvashok The preview screenshot is enough. I'm merging this pull request. Thanks for the contribution. Good job!

**Comment by abishekvashok** [comment]
Thank you

**Pull request merged**
