### PR TITLE
Preview only 1 row of csv data

### LINKED ISSUE #515: Preview of a badge shows text of more than 1 row.
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

"/n" is used to split csv text, instead it should be "\n".
**Expected behavior:**

badge preview showing only 1 csv row.
**Steps to reproduce:**

### PR DESCRIPTION
**Pull request by rupav**
Fixes #515

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x ] My branch is up-to-date with the Upstream `development` branch.
- [x ] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Previously "/n" was used and hence for preview badges, script.js  will take next line's first word too, because text splitting is done around /n.  "\n" i.e. new line character should be there instead.

### CODE REVIEW

**Comment by abishekvashok** [comment]
Yikes i can see old commits, can you properly rebase pls?

**Comment by rupav** [comment]
**Earlier**:
screenshot 2018-01-24 20 50 29
**After the fix**:
screenshot 2018-01-24 20 49 47

PS: I couldn't include above images on PR description itself, don't know why github was giving error.

**Comment by rupav** [comment]
@abishekvashok I forget to rebase origin, only rebased local 😅. Any suggestions what to do now? Squashing will suffice?

**Comment by abishekvashok** [comment]
Drop that unwanted commit, pull like:
`git pull upstream --rebase`then do a force push **after making sure** everything is fine. If that didn't help, we can do a rebase and merge.

**Comment by rupav** [comment]
@abishekvashok It worked, thanks.

**Comment by abishekvashok** [comment]
Welcome

**Comment by abishekvashok** [comment]
Thanks for the pr @rupav
Thanks for the review @S2606
:)

**Pull request merged**
