### PR TITLE
Add sample backgrounds

### LINKED ISSUE #155: Use SVG image
**I'm submitting a ...**
- [X] feature request

**Current behavior:**

Currently, we can choose from a variety of badge backgrounds.
#152 introduced a new background picture.

**Expected behavior:**

Please allow an option to
- [x] (1) choose this background picture
- [x] (2) set the desired color
- [x] (3) set an image for the conference
- [x] (4) set a heading like "Speaker" or VIP

**Steps to reproduce:**

This is a multi-issue. If you like to work in it, please say, which part you like to work on.

### PR DESCRIPTION
**Pull request by rupav**
This includes sample background with and without FOSSASIA logo, text. Color and text are editable using a text editor.

Fixes #155 checklist- 1,2 and 4.
Can be used for solving issue #153  4th.

#### Checklist

- [ x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x ] My branch is up-to-date with the Upstream `development` branch.
- [x ] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Changes proposed are written in details in the folder itself, with file name : 'Documentation for Use.docx', thus providing the Documentation.

### CODE REVIEW

**Comment by rupav** [comment]
@niccokunzmann  @pushkalkatara  @gabru-md please have a look.
related to issues #155  and #153

**Comment by gabru-md** [comment]
@rupav There is already a `sample` folder in badgeyay.
Why add another one?
I'm Proposing some changes kindly see them

**Comment by rupav** [comment]
@gabru-md  done.

**Comment by gabru-md** [comment]
@rupav Please close this PR

**Pull request closed without merging**
