### PR TITLE
Remove redundant lines

### LINKED ISSUE #301: Remove redundant lines from Travis
**I'm submitting a ...**
- [ ] bug report
- [X] feature request

### PR DESCRIPTION
**Pull request by S2606**
Fixes #301 

#### Checklist

- [X] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [X] My branch is up-to-date with the Upstream `development` branch.
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by S2606** [comment]
@gabru-md Please review

**Comment by vaibhavsingh97** [comment]
@S2606 Please wait for atleast 2 reviews before merging

**Comment by S2606** [comment]
@vaibhavsingh97 Sorry for that.

**Comment by gabru-md** [comment]
Good. @S2606 please wait for atleast 2 reviews.

**Comment by S2606** [comment]
I apologize for my mistake.

**Pull request merged**
