### PR TITLE
fixes #76 - added new version of merge_badges script

### LINKED ISSUE #76: Make merge_badges.py independent of linux commands
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/badgeyay

**Current behavior:**
merge_badges.py contains linux commands being executed from python code, this makes the app dependent on os.

**Expected behavior:**
Remove the linux commands and use corresponding python code

### PR DESCRIPTION
**Pull request by djmgit**
Fixes issue #76, added new version of merge_badges python
script which is independent of pdftk dependency and all
the linux commands related to it.

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by djmgit** [comment]
@niccokunzmann  @jajodiaraghav I have added a new version of merge_badges script
I have removed pdftk dependency and I have used pypdf2 library instead. This has removed the linux commands used in the context of pdftk previously.

**Comment by jajodiaraghav** [comment]
Great work @djmgit !
Although, we recently made a few important changes to merge_badges.py file (For instance in line 14 and 23). Can you please sync those changes in this version too.
Thanks a lot :)

**Comment by jajodiaraghav** [comment]
@djmgit Awesome! Thanks
Merging 🚀

**Comment by djmgit** [comment]
@jajodiaraghav done!

**Comment by djmgit** [comment]
@jajodiaraghav  I was trying to remove rsvg dependency by trying to do the pdf generation using python libraries. I tried svglib, however it is unable to render the background (externally loaded) image into pdf. I tried using cairosvg, however it has got some installation issues with pip3. I am searching for alternatived. Do you have anything else in mind?? :)

**Comment by djmgit** [comment]
I am working on removing dependency on linux zip command

**Comment by jajodiaraghav** [comment]
I tried searching for such a package but all in vain. There was one package that I liked but it isn't free :(

**Comment by gabru-md** [comment]
I can work on this one @jajodiaraghav .
Converting the linux zip command into python command.

**Comment by jajodiaraghav** [comment]
That's great. Just ask if djmgit is working on this. You two can also collaborate on this too :)

**Comment by gabru-md** [comment]
@djmgit may i work on this ? If you're not working ?

**Comment by djmgit** [comment]
@gabru-md I have not started working on it yet,  please go ahead :)

**Comment by gabru-md** [comment]
Thanks

**Pull request merged**
