### PR TITLE
Server is now running:  python3 main.py is not giving error

### LINKED ISSUE #97: main.py not running, no module named urllib2
**I'm submitting a ...**  (check one with "x")
- [x] bug report
**Current behavior:**
workspace 1_012
Can't run file main.py
**Expected behavior:**
File should run server with http://127.0.0.1:5000

**Steps to reproduce:**
Changing urllib2 to urllib.request in generate_csv_eventyay.py  will resolve this error.

### PR DESCRIPTION
**Pull request by nanspro**
Fixes #97 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
Server is starting to run now

#### Changes proposed in this pull request:

-Changing urllib2 to urllib.request in generate_csv_eventyay.py

### CODE REVIEW

**Comment by niccokunzmann** [comment]
Thanks!

**Comment by nanspro** [comment]
@niccokunzmann  can you tell me what type of commit messages i should write in general?

**Comment by niccokunzmann** [comment]
> A patch commit message MUST consist of a single short (less than 50 characters) line stating the problem ("Problem: ...") being solved, followed by a blank line and then the proposed solution ("Solution: ...").

https://rfc.zeromq.org/spec:42/C4/

This is one thing. Many people describe the change. I think, the above is better.

**Comment by nanspro** [comment]
Thanks @niccokunzmann

**Pull request merged**
