### PR TITLE
Fixes #884: Centering form contents on the terms of v1

### LINKED ISSUE #884: Centering Form accrdoing to v1
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

Centering the form contents on the terms of v1. 

__Yes__ sending PR for the same

### PR DESCRIPTION
**Pull request by yashLadha**
Fixes #884

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] I have added necessary documentation (if appropriate)

### Preview Link 

- **Replace XXX with your PR no**
- Link to live demo: http://pr-886-fossasia-badgeyay.surge.sh  

#### Changes proposed in this pull request:

- Centering frontend form on the terms of v1
- Allowing enter key to submit form at login

### CODE REVIEW

**Comment by yashLadha** [comment]
Please review @djmgit @ParthS007 @gabru-md @vaibhavsingh97

**Comment by djmgit** [comment]
@ParthS007 please take a look at travis.

**Comment by yashLadha** [comment]
Ping @djmgit please merge it

**Comment by yashLadha** [comment]
cc @djmgit  I am already prepared my another PR extending this PR. So can it please be merged. Thanks

**Comment by gabru-md** [comment]
Can be merged i suppose

**Pull request merged**
