### PR TITLE
Updated backend file names as per python coding standards.

### PR DESCRIPTION
**Pull request by sangeetagupta2068**
Fixes #

#### Changes proposed in this pull request:

-
-
-

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by kushthedude** [comment]
What's the issue in camel case ?

**Comment by impiyush83** [comment]
@kushthedude  https://softwareengineering.stackexchange.com/questions/308972/python-file-naming-convention

**Comment by impiyush83** [comment]
@kushthedude  I have observed in the repo many inconsistencies in variable names also. In some places, they are camelcase and in some with snake case. I think this is a valid issue with low priority.

**Comment by rajvaibhavdubey** [comment]
I don't think this is required. 
Closing :+1:

**Pull request closed without merging**
