### PR TITLE
Fix merge_badges.py error

### PR DESCRIPTION
**Pull request by djmgit**
Fix issue #269, merge_badges.py no more shows error.

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by djmgit** [comment]
@vaibhavsingh97 i guess this is a separate issue, I am facing this problem from before making any changes to merge_badges.py. In fact I was going to create an issue for that !

**Comment by vaibhavsingh97** [comment]
@djmgit I had rechecked and i am not facing this issue and i only face issue when i pulled this PR. Can you please tell me steps to reproduce the issue 😄 
After confirmation, we can create new issue and fix the issue on priority

**Comment by djmgit** [comment]
@vaibhavsingh97  
- move a copy of exhibitor.png.csv (or any other sample) to uploads directory, then execute 
  merge_badges.py -p
- **expected** : badges should be create
- **actual outcome**: an exception is encountered as shown in this terminal -  https://github.com/fossasia/badgeyay/issues/269

**Comment by djmgit** [comment]
@vaibhavsingh97 regarding the problem which you mentioned above(bad request), I started facing that error after i pulled the latest code.

**Comment by vaibhavsingh97** [comment]
@djmgit Open new issue, and add necessary logs 😄

**Comment by djmgit** [comment]
@vaibhavsingh97 sure :)

**Pull request merged**
