### PR TITLE
Added some hover effects on navbar elements.

### LINKED ISSUE #1870: On hover effect on NavBar elements
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behaviour:**

**Expected behaviour:**

**Steps to reproduce:**
1) Go to http://badgeyay.com/
2) Hover on any NavBar element.

**Would you like to work on the issue?**
Yes, I would like to work on this issue.

### PR DESCRIPTION
**Pull request by Puranjay25**
Fixes #1870

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- On navbar elements I have added some hover effects to make them more attractive.

### Screenshots for the change
hover
-
-

### CODE REVIEW

**Comment by Puranjay25** [comment]
@sk9331657 the codeacy error is about line space. In my text editor there is no line space after line #31  but when I commit my changes the line space gets active at the same line.
What should I do now?

**Comment by Puranjay25** [comment]
@sk9331657 Codacy error is now fixed.

**Comment by mariobehling** [comment]
Please provide screenshots and link to test deployment.

**Comment by Puranjay25** [comment]
@mariobehling I have added the screenshot for the same.

**Pull request closed without merging**
