### PR TITLE
Fix Travis

### LINKED ISSUE #149: Fix Travis tests
**I'm submitting a ...**
- [X] bug report

**Current behavior:**

Currently, travis is failing.
https://travis-ci.org/fossasia/badgeyay/builds/278248341?utm_source=github_status&utm_medium=notification

**Expected behavior:**

Travis should run all the tests #147 and succeed.

**Steps to reproduce:**

Please create a pull request to work on this issue and submit commits which fix the errors.

### PR DESCRIPTION
**Pull request by S2606**
Fixes #149 

#### Checklist

- [X] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [X] My branch is up-to-date with the Upstream `development` branch.
- [X] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by S2606** [comment]
@fossasia/badgeyay-admin We have a problem with loading custom fonts as the only reason for travis CI not to work is this. Could anyone suggest a way for faster loading custom fonts??

**Comment by jajodiaraghav** [comment]
@S2606 Are you sure Travis is failing due to custom-fonts, and not something else?

If this is the case, then we can merge this. How can we fix the font issue?

**Comment by vaibhavsingh97** [comment]
@jajodiaraghav I don't think so please don't merge this

**Comment by vaibhavsingh97** [comment]
@S2606 Any lead on this issue?

**Comment by S2606** [comment]
@vaibhavsingh97 No and wbu??Did you get something in stackoverflow??

**Comment by S2606** [comment]
@jajodiaraghav can you please tell me where we using .ttf files??

**Comment by jajodiaraghav** [comment]
We are not directly using TTF, although Bootstrap fetches ttf in it's CSS files.

**Comment by vaibhavsingh97** [comment]
@S2606 Nope 😞 I will not able to solve this right now but i will make sure i will sove this in weekend

**Comment by S2606** [comment]
@vaibhavsingh97 How about caching .ttf files?? is it good idea?

**Comment by vaibhavsingh97** [comment]
@S2606 If you this can fix, then yes 👍

**Comment by S2606** [comment]
I am closing this because @mohdomama has fixed this. Credits to him!!

**Pull request closed without merging**
