### PR TITLE
Removed redundant code from main.py

### PR DESCRIPTION
**Pull request by jajodiaraghav**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Removed redundant code from main.py

### CODE REVIEW

**Comment by djmgit** [comment]
@jajodiaraghav PR looks good, could remove this line : ``` SCRIPT = os.path.join(APP_ROOT, 'merge_badges.sh')``` from main.py too as a part of this PR. This line is not required anymore.

**Comment by jajodiaraghav** [comment]
Yeah Sure @djmgit 
I must've missed that line. Updating in a moment.

**Comment by jajodiaraghav** [comment]
Updated!

**Comment by vaibhavsingh97** [comment]
Thanks @jajodiaraghav 👍

**Pull request merged**
